const alleHoerenPruefungen = [
    {
        id: 1,
        niveau: "B2",
        name: "Đề 1: Gesellschaft & Wirtschaft (Goethe B2)",
        teile: [
            {
                teilName: "Teil 1 - Text 1: Die Renaissance des Handwerks",
                audioSrc: "audio/de1-teil1-text1.mp3",
                transcript: `Lange Zeit galt eine akademische Ausbildung als das Nonplusultra für eine erfolgreiche Karriere. Doch das Blatt wendet sich. Angesichts überfüllter Hörsäle und einer wachsenden Zahl an Absolventen in Geisteswissenschaften, die prekäre Beschäftigungsverhältnisse vorfinden, rückt das Handwerk wieder in den Fokus. Entgegen dem Klischee von schwerer körperlicher Arbeit bei geringem Lohn, bietet der Sektor heute dank Digitalisierung und Smart-Home-Technologien hochkomplexe Aufgabenbereiche. Die Vergütung für spezialisierte Fachkräfte übersteigt mittlerweile oft das Einstiegsgehalt von Master-Absolventen. Dennoch bleibt der Nachwuchsmangel bestehen, da das gesellschaftliche Ansehen der praktischen Arbeit nur zögerlich dem finanziellen Anreiz folgt.`,
                fragen: [
                    { frage: "1. Warum entscheiden sich wieder mehr Menschen für eine handwerkliche Ausbildung?", antworten: ["A. Weil ein Studium heute keine Garantie mehr für eine stabile Anstellung ist.", "B. Weil die Arbeit im Handwerk körperlich weniger anstrengend geworden ist als früher.", "C. Weil die Hörsäle an den Universitäten aus Sicherheitsgründen geschlossen wurden."], richtig: 0, begruendung: "Text: 'Angesichts überfüllter Hörsäle und Absolventen, die prekäre Beschäftigungsverhältnisse vorfinden, rückt das Handwerk wieder in den Fokus.'" },
                    { frage: "2. Was sagt der Text über die Bezahlung im Handwerk aus?", antworten: ["A. Sie ist immer noch niedriger als in akademischen Berufen.", "B. Spezialisierte Handwerker verdienen oft mehr als Berufseinsteiger mit Universitätsabschluss.", "C. Die Löhne sind nur gestiegen, weil die Digitalisierung Kosten spart."], richtig: 1, begruendung: "Text: 'Die Vergütung für spezialisierte Fachkräfte übersteigt mittlerweile oft das Einstiegsgehalt von Master-Absolventen.'" },
                    { frage: "3. Was ist das Hauptproblem für die Zukunft des Sektors?", antworten: ["A. Dass die Digitalisierung viele Arbeitsplätze überflüssig macht.", "B. Dass junge Menschen das Image des Handwerks skeptisch sehen.", "C. Dass es zu viele staatliche Förderungen gibt."], richtig: 1, begruendung: "Text: 'Dennoch bleibt der Nachwuchsmangel bestehen, da das gesellschaftliche Ansehen der praktischen Arbeit nur zögerlich dem finanziellen Anreiz folgt.'" }
                ]
            },
            {
                teilName: "Teil 1 - Text 2: Greenwashing",
                audioSrc: "audio/de1-teil1-text2.mp3",
                transcript: `Wer heute einkauft, trifft auf ein Meer von 'Öko'-Labeln. Doch Vorsicht ist geboten: Der Begriff 'klimaneutral' ist gesetzlich kaum geschützt. Viele Konzerne investieren lieber in Marketingkampagnen und den Kauf von zweifelhaften CO2-Zertifikaten, statt ihre Produktionsketten tatsächlich umzustrukturieren. Für den Verbraucher ist es fast unmöglich, echte Nachhaltigkeit von geschickter PR zu unterscheiden. Experten fordern daher eine strengere Zertifizierungspflicht durch unabhängige staatliche Organe, um die inflationäre Verwendung von Umweltversprechen einzudämmen. Solange dies nicht geschieht, bleibt der Griff zum 'grünen' Produkt oft eine reine Gewissensberuhigung ohne ökologischen Mehrwert.`,
                fragen: [
                    { frage: "4. Was kritisiert der Text am Begriff „klimaneutral“?", antworten: ["A. Nur für Schwerindustrie verwendet.", "B. Dass die gesetzlichen Regelungen für seine Verwendung unzureichend sind.", "C. Verbraucher ignorieren den Begriff."], richtig: 1, begruendung: "Text: 'Der Begriff klimaneutral ist gesetzlich kaum geschützt.'" },
                    { frage: "5. Wie gehen viele Konzerne mit dem Thema Nachhaltigkeit um?", antworten: ["A. Sie verändern ihre gesamte Produktion.", "B. Sie setzen auf Werbung und Ausgleichszahlungen statt auf reale Veränderungen.", "C. Arbeiten mit staatlichen Organen zusammen."], richtig: 1, begruendung: "Text: 'Viele Konzerne investieren lieber in Marketingkampagnen und den Kauf von zweifelhaften CO2-Zertifikaten...'" },
                    { frage: "6. Welche Lösung wird im Text vorgeschlagen?", antworten: ["A. Verbraucher sollen sich informieren.", "B. Preise drastisch erhöhen.", "C. Eine verpflichtende Überprüfung durch neutrale Instanzen muss eingeführt werden."], richtig: 2, begruendung: "Text: 'Experten fordern daher eine strengere Zertifizierungspflicht durch unabhängige staatliche Organe...'" }
                ]
            },
            {
                teilName: "Teil 1 - Text 3: Das Ende des Bargelds?",
                audioSrc: "audio/de1-teil1-text3.mp3",
                transcript: `In skandinavischen Ländern ist es bereits Alltag, in Deutschland hingegen ein hochemotionales Thema: Die Abschaffung des Bargelds. Befürworter verweisen auf die Effizienz und die Bekämpfung von Schwarzarbeit. Kritiker jedoch sehen im Verschwinden von Münzen und Scheinen den Weg in den 'gläsernen Bürger'. Jede Transaktion hinterlässt eine digitale Spur, die von Banken und potenziell auch vom Staat ausgewertet werden kann. Zudem warnt der Einzelhandelsverband vor einer sozialen Ausgrenzung älterer Generationen, für die digitale Bezahlsysteme oft eine unüberwindbare Barriere darstellen. Die Debatte zeigt: Es geht um weit mehr als nur um Bequemlichkeit beim Bezahlen.`,
                fragen: [
                    { frage: "7. Welchen Vorteil nennen die Befürworter der bargeldlosen Gesellschaft?", antworten: ["A. Förderung der Anonymität.", "B. Eine effektivere Kontrolle von illegalen Beschäftigungsverhältnissen.", "C. Einfacher für ältere Menschen."], richtig: 1, begruendung: "Text: 'Befürworter verweisen auf die Effizienz und die Bekämpfung von Schwarzarbeit.'" },
                    { frage: "8. Was ist die größte Sorge der Kritiker?", antworten: ["A. Zu hohe Gebühren.", "B. Dass der Datenschutz verloren geht und das Finanzverhalten überwachbar wird.", "C. Technik bei Stromausfall."], richtig: 1, begruendung: "Text: 'Kritiker jedoch sehen im Verschwinden von Münzen und Scheinen den Weg in den gläsernen Bürger.'" },
                    { frage: "9. Warum warnt der Einzelhandelsverband vor der Umstellung?", antworten: ["A. Weniger Gewinn.", "B. Weil bestimmte Bevölkerungsgruppen vom wirtschaftlichen Leben abgeschnitten werden könnten.", "C. Fehlende Infrastruktur."], richtig: 1, begruendung: "Text: 'Zudem warnt der Einzelhandelsverband vor einer sozialen Ausgrenzung älterer Generationen...'" }
                ]
            },
            {
                teilName: "Teil 1 - Text 4: Urban Farming",
                audioSrc: "audio/de1-teil1-text4.mp3",
                transcript: `Die Idee, Gemüse direkt auf den Dächern von Hochhäusern anzubauen, klingt nach einer ökologischen Revolution. Doch bei näherer Betrachtung der Energiebilanz schwindet die Euphorie oft. Während der Transportweg zwar entfällt, ist der Ressourcenverbrauch für Bewässerungssysteme und künstliche Beleuchtung in geschlossenen Räumen, dem sogenannten 'Vertical Farming', enorm. Ökonomen betonen, dass diese Methode derzeit nur für hochpreisige Nischenprodukte wie exotische Kräuter rentabel ist. Für die Grundversorgung der städtischen Bevölkerung mit Weizen oder Kartoffeln bleibt die traditionelle Landwirtschaft auf dem Land vorerst unersetzlich, da die Kosten pro Quadratmeter in der Innenstadt schlichtweg zu hoch kalkuliert sind.`,
                fragen: [
                    { frage: "10. Warum ist die Energiebilanz von Urban Farming oft negativ?", antworten: ["A. Transport verbraucht Treibstoff.", "B. Weil die technische Instandhaltung der Anlagen extrem viel Energie benötigt.", "C. Bauern nutzen effizientere Traktoren."], richtig: 1, begruendung: "Text: '...ist der Ressourcenverbrauch für Bewässerungssysteme und künstliche Beleuchtung in geschlossenen Räumen enorm.'" },
                    { frage: "11. Für welche Produkte eignet sich Vertical Farming momentan am ehesten?", antworten: ["A. Preisgünstige Grundnahrungsmittel.", "B. Für spezielle Produkte, die zu einem hohen Preis verkauft werden können.", "C. Obstsorten."], richtig: 1, begruendung: "Text: '...derzeit nur für hochpreisige Nischenprodukte wie exotische Kräuter rentabel ist.'" },
                    { frage: "12. Was ist das größte Hindernis für großflächigen Anbau in Städten?", antworten: ["A. Mangel an Fachkräften.", "B. Die hohen finanziellen Belastungen durch die Immobilienpreise in der Stadt.", "C. Widerstand der Landwirte."], richtig: 1, begruendung: "Text: '...da die Kosten pro Quadratmeter in der Innenstadt schlichtweg zu hoch kalkuliert sind.'" }
                ]
            },
            {
                teilName: "Teil 1 - Text 5: Lebenslanges Lernen",
                audioSrc: "audio/de1-teil1-text5.mp3",
                transcript: `In einer sich rasant wandelnden Arbeitswelt verliert das einmal erworbene Diplom immer schneller an Wert. Das Konzept des 'lebenslangen Lernens' ist daher kein bloßes Schlagwort mehr, sondern eine Überlebensstrategie. Doch die Verantwortung dafür wird zunehmend auf das Individuum abgewälzt. Während Unternehmen früher interne Fortbildungen finanzierten, wird heute oft erwartet, dass Arbeitnehmer sich in ihrer Freizeit und auf eigene Kosten qualifizieren. Experten warnen vor einer 'Bildungsschere': Wer bereits gut verdient und Zeit hat, investiert in Wissen, während Geringverdiener in ihren veralteten Berufsfeldern gefangen bleiben. Staatliche Bildungsurlaube könnten hier ein Korrektiv sein, werden aber bisher kaum in Anspruch genommen.`,
                fragen: [
                    { frage: "13. Wie hat sich die Bedeutung von Bildungsabschlüssen verändert?", antworten: ["A. Ein Diplom garantiert lebenslange Sicherheit.", "B. Das Wissen aus der Ausbildung veraltet heute wesentlich schneller als früher.", "C. Universitätsabschlüsse sind wertvoller."], richtig: 1, begruendung: "Text: 'In einer sich rasant wandelnden Arbeitswelt verliert das einmal erworbene Diplom immer schneller an Wert.'" },
                    { frage: "14. Was wird an der aktuellen Praxis der Weiterbildung kritisiert?", antworten: ["A. Zu viele Fortbildungen.", "B. Dass die Kosten und der Zeitaufwand immer häufiger bei den Angestellten liegen.", "C. Keine staatlichen Angebote."], richtig: 1, begruendung: "Text: '...wird heute oft erwartet, dass Arbeitnehmer sich in ihrer Freizeit und auf eigene Kosten qualifizieren.'" },
                    { frage: "15. Was ist das Risiko der beschriebenen „Bildungsschere“?", antworten: ["A. Dass Menschen mit geringem Einkommen den Anschluss am Arbeitsmarkt verlieren.", "B. Dass gut verdienende Arbeitnehmer nur noch lernen.", "C. Qualität der Lehre sinkt."], richtig: 0, begruendung: "Text: '...während Geringverdiener in ihren veralteten Berufsfeldern gefangen bleiben.'" }
                ]
            },
            {
                teilName: "Teil 2: Der Experten-Vortrag (Umgang mit dem Scheitern)",
                audioSrc: "audio/de1-teil2.mp3",
                transcript: `Guten Tag, meine Damen und Herren. In der heutigen Start-up-Welt wird oft das Bild des perfekten Gründers gezeichnet. Doch die Realität sieht anders aus: Über 80 % aller Neugründungen scheitern in den ersten drei Jahren. Warum ist das so?
Ein wesentlicher Aspekt ist die kulturelle Prägung. Während man in den USA ein gescheitertes Projekt oft als 'notwendige Erfahrung' im Lebenslauf verbucht, herrscht in Europa – und besonders im deutschsprachigen Raum – eine regelrechte Stigmatisierung vor. Das Problem ist hier weniger der Zugang zu Kapital, sondern die Tatsache, dass der gesellschaftliche Status extrem eng mit einer lückenlosen Erfolgsbiografie verknüpft ist. Wer einmal scheitert, gilt oft als 'beschädigt', was psychologisch einen enormen Druck aufbaut.
Was wir also brauchen, ist eine 'positive Fehlerkultur'. Das bedeutet ausdrücklich nicht, dass wir Nachlässigkeit fördern oder Fehler feiern sollen. Vielmehr geht es darum, eine Umgebung zu schaffen, in der Missgeschicke nicht vertuscht, sondern transparent analysiert werden. Nur so lassen sich Defizite im System – und nicht nur beim Individuum – identifizieren.
Ein klassischer Fehler, den ich immer wieder beobachte, ist die sogenannte 'Eskalation des Commitments'. Viele Gründer verlieben sich so sehr in ihre Vision, dass sie Warnsignale des Marktes ignorieren. Sie verbrennen Kapital für ein Produkt, das eigentlich niemand braucht, anstatt frühzeitig den Kurs zu ändern. Hier bietet die Digitalisierung heute enorme Chancen: Dank Echtzeit-Datenanalysen lassen sich Fehlentwicklungen beinahe sofort erkennen und korrigieren, bevor sie existenzbedrohend werden.
Für etablierte Großkonzerne ist dies oft schwierig, da ihre starren Hierarchien Innovationen hemmen. Mein Rat an diese Firmen: Schaffen Sie geschützte Räume, kleine 'Experimentier-Inseln', in denen Teams völlig autark wie junge Start-ups agieren können, ohne den Ballast der Konzernverwaltung.
Lassen Sie mich zum Schluss eines betonen: Scheitern an sich ist kein Verdienst. Es wird erst dann zu einem Mehrwert für die Karriere oder das Unternehmen, wenn man die intellektuelle Disziplin besitzt, die Ursachen schonungslos aufzuarbeiten. Ohne Reflexion ist ein Misserfolg schlichtweg nur verlorene Zeit.`,
                fragen: [
                    { frage: "16. Warum ist die „Fear of Failure“ in Europa ausgeprägter als in den USA?", antworten: ["A. Weniger staatliche Unterstützung.", "B. Weil das soziale Ansehen in Europa stärker an beruflichen Erfolg gekoppelt ist.", "C. Schwerere Kreditvergabe."], richtig: 1, begruendung: "Vortrag: '...die Tatsache, dass der gesellschaftliche Status extrem eng mit einer lückenlosen Erfolgsbiografie verknüpft ist.'" },
                    { frage: "17. Was versteht der Redner unter einer „positiven Fehlerkultur“?", antworten: ["A. Fehler absichtlich machen.", "B. Dass Misserfolge offen kommuniziert werden, um systemische Schwachstellen zu finden.", "C. Mitarbeiter nicht haftbar machen."], richtig: 1, begruendung: "Vortrag: '...eine Umgebung zu schaffen, in der Missgeschicke nicht vertuscht, sondern transparent analysiert werden.'" },
                    { frage: "18. Welchen Fehler machen viele Gründer laut dem Experten in der Anfangsphase?", antworten: ["A. Zu viel Geld in Marketing.", "B. Sie halten zu lange an einer ursprünglichen Idee fest, die am Markt vorbeigeht.", "C. Zu viele Mitarbeiter."], richtig: 1, begruendung: "Vortrag: 'Viele Gründer verlieben sich so sehr in ihre Vision, dass sie Warnsignale des Marktes ignorieren.'" },
                    { frage: "19. Wie beeinflusst die Digitalisierung den Umgang mit Fehlern?", antworten: ["A. Durch Datenanalysen können Fehlentscheidungen heute schneller korrigiert werden.", "B. Mitarbeiter verstecken Fehler.", "C. Größere Schäden."], richtig: 0, begruendung: "Vortrag: 'Dank Echtzeit-Datenanalysen lassen sich Fehlentwicklungen beinahe sofort erkennen...'" },
                    { frage: "20. Was empfiehlt der Experte etablierten Großunternehmen?", antworten: ["A. Fokus auf Tradition.", "B. Kleine, unabhängige Teams zu bilden, die wie Start-ups agieren dürfen.", "C. Hierarchien verstärken."], richtig: 1, begruendung: "Vortrag: 'Schaffen Sie geschützte Räume, kleine Experimentier-Inseln, in denen Teams völlig autark wie junge Start-ups agieren können...'" },
                    { frage: "21. Welches Fazit zieht der Redner am Ende seines Vortrags?", antworten: ["A. Dass Scheitern nur dann wertvoll ist, wenn eine tiefgreifende Analyse erfolgt.", "B. Jeder Gründer muss scheitern.", "C. Politik soll Risiken übernehmen."], richtig: 0, begruendung: "Vortrag: 'Es wird erst dann zu einem Mehrwert... wenn man die intellektuelle Disziplin besitzt, die Ursachen schonungslos aufzuarbeiten.'" }
                ]
            },
            {
                teilName: "Teil 3: Erweiterte Diskussion (Wer sagt was?)",
                audioSrc: "audio/de1-teil3.mp3",
                transcript: `Frau Weber: Guten Abend. In unserer heutigen Debatte geht es um das Ende einer Ära. Viele große Konzerne rufen ihre Belegschaft aus dem Homeoffice zurück in die Bürotürme. Frau Lange, Sie als Gründerin eines Software-Unternehmens halten das für einen Rückschritt, oder?
Frau Lange: Absolut. Wir befinden uns in einem globalen Wettbewerb um Fachkräfte. Wer heute von hochqualifizierten Programmierern verlangt, zwei Stunden täglich im Stau zu stehen, nur um an einem Schreibtisch zu sitzen, den er auch zu Hause hat, der handelt schlichtweg anachronistisch. Die Flexibilität, das "Arbeiten von überall", ist mittlerweile das schlagkräftigste Argument in unseren Bewerbungsgesprächen. Wer das ignoriert, wird den Fachkräftemangel in seiner härtesten Form spüren.
Dr. Schmidt: Wenn ich da kurz einhaken darf, Frau Lange. Das klingt in der Theorie der New-Work-Blase wunderbar. Aber schauen wir uns doch die soziologischen Fakten an. Ein Unternehmen ist mehr als eine Ansammlung von Einzelleistungen. Wir beobachten eine massive Erosion der Firmenkultur. Die Bindung an den Arbeitgeber schwindet, wenn der Kollege nur noch ein flackerndes Bild im Video-Call ist. Diese soziale Vereinsamung führt dazu, dass Mitarbeiter viel schneller kündigen, weil die emotionale Barriere fehlt.
Frau Weber: Aber ist nicht die Produktivität im Homeoffice laut Studien sogar gestiegen?
Dr. Schmidt: Das ist ein Trugschluss. Die quantitative Abarbeitung von Routineaufgaben mag funktionieren. Aber die qualitative Innovation, der Geistesblitz beim zufälligen Treffen im Flur, der lässt sich nicht digital simulieren. Kreativität ist ein chaotischer, physischer Prozess. Zoom-Meetings sind zu strukturiert für echte Innovation. Zudem darf man die prekäre Ergonomie in vielen Privathaushalten nicht vergessen – ein Küchentisch ersetzt kein professionelles Büro, was langfristig zu gesundheitlichen Ausfällen führt.
Frau Lange: Aber Herr Dr. Schmidt, das ist doch ein Scheinargument. Die Verantwortung für die Ausstattung kann man teilen. Der Kernpunkt ist doch die Kontrollillusion des Management. Viele Führungskräfte haben schlicht Angst vor dem Machtverlust, wenn sie ihre Mitarbeiter nicht mehr physisch "überwachen" können. Wir müssen weg von der "Absitz-Kultur". Führung im digitalen Zeitalter bedeutet, klare Zielvorgaben zu machen und die Qualität des Outputs zu bewerten, statt die Stunden auf dem Bürostuhl zu zählen. Vertrauen muss die Basis sein, nicht Überwachung.
Frau Weber: Dr. Schmidt, wie reagieren Sie auf den Vorwurf des Kontrollwahns?
Dr. Schmidt: Es geht nicht um Kontrolle, sondern um Fürsorge und Struktur. Wenn Berufs- und Privatleben verschwimmen, wenn abends um 22 Uhr noch Mails gecheckt werden, dann brennen die Leute aus. Die räumliche Trennung zwischen "Arbeitswelt" und "Rückzugsort" ist eine Errungenschaft des Arbeitnehmerschutzes, die wir gerade leichtfertig opfern.
Frau Lange: Einverstanden, die Entgrenzung ist eine Gefahr. Aber die Lösung ist nicht der Zwang zurück ins Büro, sondern eine neue Lernkultur. Übrigens profitieren auch die Firmen finanziell: Wer weniger Präsenzfläche braucht, senkt seine Mietkosten drastisch – ein Faktor, den gerade Controller in der aktuellen Wirtschaftslage nicht ignorieren sollten.
Frau Weber: Wenn wir ein Fazit ziehen: Ist die reine Präsenzpflicht tot?
Frau Lange: Ja, Flexibilität ist die Zukunft. Ein hybrides Modell, bei dem man sich gezielt für Workshops trifft, aber für die Konzentrationsarbeit zu Hause bleibt, ist der einzige Weg, der beide Seiten zufriedenstellt.
Dr. Schmidt: Nun, wenn man "Hybrid" so definiert, dass der Fokus wieder auf der Qualität der persönlichen Begegnung liegt, kann ich mit diesem Kompromiss leben. Er vereint die notwendige Struktur mit der modernen Freiheit.`,
                fragen: [
                    { frage: "22. Die soziale Isolierung im Homeoffice schadet der Identifikation mit dem Betrieb.", antworten: ["Frau Weber", "Dr. Schmidt", "Frau Lange"], richtig: 1, begruendung: "Dr. Schmidt: 'Diese soziale Vereinsamung führt dazu, dass Mitarbeiter viel schneller kündigen...'" },
                    { frage: "23. Kreative Prozesse lassen sich nicht erfolgreich in digitale Formate pressen.", antworten: ["Frau Weber", "Dr. Schmidt", "Frau Lange"], richtig: 1, begruendung: "Dr. Schmidt: 'Kreativität ist ein chaotischer, physischer Prozess. Zoom-Meetings sind zu strukturiert für echte Innovation.'" },
                    { frage: "24. Die Wahl des Arbeitsorts ist heute ein entscheidender Faktor im Recruiting.", antworten: ["Frau Weber", "Dr. Schmidt", "Frau Lange"], richtig: 2, begruendung: "Frau Lange: 'Die Flexibilität... ist mittlerweile das schlagkräftigste Argument in unseren Bewerbungsgesprächen.'" },
                    { frage: "25. Das Festhalten an Anwesenheitskontrolle ist ein Zeichen von mangelnder Modernität.", antworten: ["Frau Weber", "Dr. Schmidt", "Frau Lange"], richtig: 2, begruendung: "Frau Lange: 'Der Kernpunkt ist doch die Kontrollillusion des Managements... Wir müssen weg von der Absitz-Kultur.'" },
                    { frage: "26. Die häusliche Umgebung bietet oft keine professionellen Arbeitsbedingungen.", antworten: ["Frau Weber", "Dr. Schmidt", "Frau Lange"], richtig: 1, begruendung: "Dr. Schmidt: 'Zudem darf man die prekäre Ergonomie in vielen Privathaushalten nicht vergessen...'" },
                    { frage: "27. Nur ein hybrides Modell wird den unterschiedlichen Bedürfnissen gerecht.", antworten: ["Frau Weber", "Dr. Schmidt", "Frau Lange"], richtig: 2, begruendung: "Frau Lange: 'Ein hybrides Modell... ist der einzige Weg, der beide Seiten zufriedenstellt.'" },
                    { frage: "28. Das Management muss die Leistung anhand von Resultaten neu definieren.", antworten: ["Frau Weber", "Dr. Schmidt", "Frau Lange"], richtig: 2, begruendung: "Frau Lange: 'Führung im digitalen Zeitalter bedeutet, klare Zielvorgaben zu machen und die Qualität des Outputs zu bewerten...'" },
                    { frage: "29. Homeoffice spart den Unternehmen langfristig erhebliche Fixkosten für Büromieten.", antworten: ["Frau Weber", "Dr. Schmidt", "Frau Lange"], richtig: 2, begruendung: "Frau Lange: 'Wer weniger Präsenzfläche braucht, senkt seine Mietkosten drastisch...'" },
                    { frage: "30. Die Trennung von Privat- und Berufsleben wird durch Remote Work gefährlich instabil.", antworten: ["Frau Weber", "Dr. Schmidt", "Frau Lange"], richtig: 1, begruendung: "Dr. Schmidt: 'Wenn Berufs- und Privatleben verschwimmen... dann brennen die Leute aus.'" }
                ]
            },
            {
                teilName: "Teil 4: Der Experten-Vortrag (Attention Economy)",
                audioSrc: "audio/de1-teil4.mp3",
                transcript: `Sehr geehrte Damen und Herren, wir leben in einer Ära, in der nicht mehr das Kapital oder der Rohstoff Öl die wertvollsten Währungen sind. In unserer voll vernetzten Welt ist es die menschliche Aufmerksamkeit. Wir sprechen von der 'Attention Economy'.
Das Paradoxon unserer Zeit ist: Während die Menge an verfügbaren Daten exponentiell wächst, bleibt das menschliche Gehirn in seiner Kapazität, diese zu verarbeiten, biologisch limitiert. Plattformen wie TikTok, Instagram oder YouTube konkurrieren nicht nur um unser Geld, sondern um jede freie Sekunde unseres Bewusstseins. Dabei bedienen sie sich neurobiologischer Mechanismen: Durch algorithmische Belohnungssysteme wird in unserem Gehirn Dopamin ausgeschüttet – jedes 'Like', jede Benachrichtigung fungiert wie ein kleiner digitaler Spielautomat.
Besonders perfide ist das 'Infinite Scrolling'. Es ist kein Zufall, dass digitale Feeds kein Ende haben. Wo früher ein Zeitungsartikel endete oder ein Buchkapitel abgeschlossen war, gibt es heute keinen natürlichen Stopp-Moment mehr. Das führt dazu, dass wir in einen Zustand der kognitiven Trance verfallen. Die Folge ist eine Erosion unserer Fähigkeit zur tiefen Kontemplation. Wir verlernen das 'Deep Reading', das Versinken in komplexe Gedankengänge, und gewöhnen uns an eine fragmentierte, oberflächliche Wahrnehmung.
Dies hat auch gesellschaftliche Sprengkraft. Der Journalismus steht unter dem Diktat der Klickzahlen. Eine komplexe Analyse verkauft sich schlechter als eine reißerische Schlagzeile. So wird der öffentliche Diskurs zunehmend emotionalisiert und radikalisiert.
Was also tun? Wir können das Rad der Digitalisierung nicht zurückdrehen. Aber wir müssen eine neue Souveränität entwickeln. Das Bildungssystem ist hier in der Pflicht: Wir lehren unsere Kinder Mathematik und Sprachen, aber wir lehren sie nicht, wie man die eigene Aufmerksamkeit gegen manipulative Algorithmen verteidigt. Auch politisch brauchen wir Leitplanken – ein Verbot von Sucht-erzeugenden Designelementen in Apps wäre ein erster Schritt.
Am Ende des Tages liegt es jedoch an uns. Wir müssen begreifen, dass unsere Aufmerksamkeit unsere Freiheit ist. Wer nicht entscheidet, worauf er blickt, dem wird diese Entscheidung von einer künstlichen Intelligenz abgenommen. Und das ist ein Preis, den wir als aufgeklärte Gesellschaft nicht zahlen sollten.`,
                fragen: [
                    { frage: "31. Was ist die Kernaussage von Prof. Veith zu Beginn seines Vortrags?", antworten: ["A. Informationen sind das kostbarste Gut.", "B. In einer Welt des Informationsüberflusses ist menschliche Aufmerksamkeit die knappste Ressource.", "C. Schnelleres Lernen."], richtig: 1, begruendung: "Vortrag: 'In unserer voll vernetzten Welt ist es die menschliche Aufmerksamkeit.'" },
                    { frage: "32. Warum nutzen Plattformen „algorithmische Belohnungssysteme“?", antworten: ["A. Relevante Bildungsinhalte.", "B. Um die Verweildauer der Nutzer durch psychologische Reize künstlich zu verlängern.", "C. Gegen Falschinformationen."], richtig: 1, begruendung: "Vortrag: 'Durch algorithmische Belohnungssysteme wird in unserem Gehirn Dopamin ausgeschüttet...'" },
                    { frage: "33. Welchen Einfluss hat die „Aufmerksamkeitsökonomie“ auf den Journalismus?", antworten: ["A. Nachrichten werden kürzer und oberflächlicher, um die Klickzahlen zu erhöhen.", "B. Tiefgründige Recherchen.", "C. Höhere Qualität."], richtig: 0, begruendung: "Vortrag: 'Eine komplexe Analyse verkauft sich schlechter als eine reißerische Schlagzeile.'" },
                    { frage: "34. Was versteht der Redner unter dem Begriff „Infinite Scrolling“?", antworten: ["A. Archivierungsmethode.", "B. Ein technisches Design, das das natürliche Ende einer Informationseinheit verhindert.", "C. Lesehilfe."], richtig: 1, begruendung: "Vortrag: '...gibt es heute keinen natürlichen Stopp-Moment mehr.'" },
                    { frage: "35. Welche gesundheitlichen Folgen werden im Vortrag explizit genannt?", antworten: ["A. Rückenschmerzen.", "B. Chronische Konzentrationsstörungen und eine verminderte Fähigkeit zur Tiefenreflexion.", "C. Bessere Reaktion."], richtig: 1, begruendung: "Vortrag: 'Die Folge ist eine Erosion unserer Fähigkeit zur tiefen Kontemplation. Wir verlernen das Deep Reading...'" },
                    { frage: "36. Wie reagiert die Wirtschaft laut Prof. Veith auf diesen Trend?", antworten: ["A. Verzicht auf Werbung.", "B. Emotionale Schockmomente.", "C. Firmen investieren Milliarden, um Sekunden der menschlichen Konzentration zu „kaufen“."], richtig: 2, begruendung: "Vortrag: 'Plattformen... konkurrieren nicht nur um unser Geld, sondern um jede freie Sekunde unseres Bewusstseins.'" },
                    { frage: "37. Was kritisiert der Experte am Bildungssektor?", antworten: ["A. Zu wenig Computer.", "B. Dass Lehrpläne die Vermittlung von „Aufmerksamkeitsdisziplin“ bisher vernachlässigen.", "C. Lehrer im Social Media."], richtig: 1, begruendung: "Vortrag: 'Wir lehren unsere Kinder Mathematik... aber wir lehren sie nicht, wie man die eigene Aufmerksamkeit verteidigt.'" },
                    { frage: "38. Welchen Lösungsvorschlag macht der Redner auf individueller Ebene?", antworten: ["A. Kompletter Verzicht.", "B. Die bewusste Gestaltung von „digitalen Fastenperioden“ und analogen Freiräumen.", "C. Apps blockieren."], richtig: 1, begruendung: "Vortrag: 'Wir müssen eine neue Souveränität entwickeln...'" },
                    { frage: "39. Welche Rolle sollte der Staat laut Prof. Veith einnehmen?", antworten: ["A. Netzwerke verbieten.", "B. Er muss strengere Richtlinien für manipulatives Design in der Softwareentwicklung vorgeben.", "C. Kostenloses Internet."], richtig: 1, begruendung: "Vortrag: '...ein Verbot von Sucht-erzeugenden Designelementen in Apps wäre ein erster Schritt.'" },
                    { frage: "40. Welches Fazit zieht der Redner am Ende?", antworten: ["A. Digitale Revolution gescheitert.", "B. Wir müssen die Kontrolle über unsere Wahrnehmung von den Algorithmen zurückerobern.", "C. Psyche passt sich an."], richtig: 1, begruendung: "Vortrag: 'Wir müssen begreifen, dass unsere Aufmerksamkeit unsere Freiheit ist.'" }
                ]
            },
            {
                teilName: "Teil 5: Wissenschaftlicher Diskurs",
                audioSrc: "audio/de1-teil5.mp3",
                transcript: `Meine Damen und Herren, lassen Sie uns heute ein Tabu der modernen Ökonomie brechen: Das Dogma des ewigen Wachstums. Seit der industriellen Revolution ist unser gesamtes System darauf programmiert, dass das BIP (Bruttoinlandsprodukt) Jahr für Jahr steigen muss. Doch wir stoßen an die planetaren Grenzen. Das Paradoxon, das wir beobachten, ist der sogenannte 'Rebound-Effekt'. Wir bauen zwar Autos, die weniger Benzin verbrauchen, aber was passiert? Die Menschen fahren mehr Kilometer oder kaufen größere SUVs. Am Ende ist der absolute Ressourcenverbrauch höher als zuvor. Effizienz allein ist also eine Sackgasse, wenn sie nicht mit einer kulturellen Strategie der Genügsamkeit – der Suffizienz – einhergeht.
Die Verfechter des 'Grünen Wachstums' versprechen uns, dass wir Technik und Ökologie versöhnen können. Doch das ist, bei allem Respekt, eine Beruhigungspille für das schlechte Gewissen der Konsumgesellschaft. Wir können die Produktion nicht unendlich 'entkoppeln'. Jedes produzierte Gut, auch ein Elektroauto, benötigt seltene Erden, Wasser und Energie. Wir müssen uns fragen: Wann ist es genug? In der aktuellen Wirtschaftsforschung nennen wir das die 'Post-Wachstumsökonomie'. Es geht nicht um Armut, sondern um eine Befreiung vom Ballast.
(Dr. Martinez): Ich möchte Herrn Professor von Hagens hier ergänzen, aber auch einen kritischen Akzent setzen. Das Problem ist nicht nur die ökologische Grenze, sondern die psychologische Erschöpfung. Wir arbeiten 40 Stunden oder mehr, um Dinge zu kaufen, die wir nicht brauchen, um Leute zu beeindrucken, die wir nicht mögen. Das ist eine Form von Hamsterrad-Ökonomie.
Wenn wir über 'Wohlstand' reden, müssen wir ihn neu definieren. Echter Wohlstand im 21. Jahrhundert ist nicht der dritte Fernseher oder das neueste Smartphone alle zwei Jahre. Echter Wohlstand ist Zeitsouveränität. Die Fähigkeit, weniger zu arbeiten, mehr Zeit für Bildung, Familie und zivilgesellschaftliches Engagement zu haben. Doch hier liegt die Krux: Unser Renten- und Sozialsystem ist so konstruiert, dass es ohne Wachstum kollabiert. Wenn die Wirtschaft schrumpft, steigen die Arbeitslosenzahlen. Das ist die fatale Logik, aus der wir ausbrechen müssen. Wir brauchen ein System, das stabil ist, auch wenn es nicht wächst. Das erfordert eine radikale Umverteilung von Arbeit und Vermögen.
(Prof. von Hagens): Exakt. Und das führt uns zur Frage der globalen Gerechtigkeit. Wir im globalen Norden können nicht von den Schwellenländern verlangen, auf Wachstum zu verzichten, während wir unseren Lebensstandard auf Kosten ihrer Ressourcen verteidigen. Eine Post-Wachstumsgesellschaft im Westen ist die moralische Voraussetzung dafür, dass der Rest der Welt überhaupt eine Chance auf eine würdige Entwicklung hat. Wir müssen lernen, mit weniger materiellen Gütern ein besseres Leben zu führen – eine 'Eleganz des Weglassens', wenn Sie so wollen.`,
                fragen: [
                    { frage: "41. Welches Paradoxon beschreibt Prof. von Hagens zu Beginn?", antworten: ["A. Menschen konsumieren weniger.", "B. Wachstum steigt, Lebenszufriedenheit stagniert.", "C. Dass technische Innovationen den Ressourcenverbrauch nicht senken, sondern steigern."], richtig: 2, begruendung: "Prof. von Hagens: 'Das Paradoxon... ist der Rebound-Effekt... am Ende ist der absolute Ressourcenverbrauch höher als zuvor.'" },
                    { frage: "42. Was ist die Hauptkritik am „Grünen Wachstum“?", antworten: ["A. Zu teuer.", "B. Es ist eine Illusion, da die Effizienzgewinne durch Mehrkonsum aufgefressen werden.", "C. Technik nicht weit genug."], richtig: 1, begruendung: "Prof. von Hagens: 'Doch das ist... eine Beruhigungspille für das schlechte Gewissen... Wir können die Produktion nicht unendlich entkoppeln.'" },
                    { frage: "43. Welchen neuen Wohlstandsbegriff schlägt Dr. Martinez vor?", antworten: ["A. Luxusgüter.", "B. Die Souveränität über die eigene Zeit und soziale Bindungen.", "C. Grundeinkommen."], richtig: 1, begruendung: "Dr. Martinez: 'Echter Wohlstand ist Zeitsouveränität. Die Fähigkeit, weniger zu arbeiten, mehr Zeit für Bildung, Familie... zu haben.'" }
                ]
            }
        ]
    },
   {
        id: 2,
        niveau: "B2",
        name: "Đề 2: Alltag, Arbeitswelt & Gesellschaft (Goethe B2)",
        teile: [
            {
                teilName: "Teil 1 - Text 1: Fitness-Trends",
                audioSrc: "audio/de2-teil1-text1.mp3",
                transcript: "Viele melden sich im Januar voller Elan im Fitnessstudio an, doch schon im März herrscht gähnende Leere an den Geräten. Experten raten dazu, nicht sofort mit einem täglichen Hardcore-Training zu starten. Viel wichtiger als die Intensität zu Beginn ist die Regelmäßigkeit. Wer sich unrealistische Ziele setzt, verliert schnell die Lust. Stattdessen sollte man mit zwei festen Terminen pro Woche starten, die fest im Kalender stehen, als wären es wichtige Geschäftstermine.",
                fragen: [
                    { frage: "1. Was ist der häufigste Fehler bei Neujahrsvorsätzen im Sport?", antworten: ["A. Die Auswahl der falschen Sportart.", "B. Ein zu hoher und damit unrealistischer Trainingsumfang am Anfang.", "C. Dass man zu wenig Geld für ein gutes Fitnessstudio ausgibt."], richtig: 1, begruendung: "Text: 'Ein zu hoher und damit unrealistischer Trainingsumfang...'" },
                    { frage: "2. Was raten Experten für einen langfristigen Erfolg?", antworten: ["A. Dass man täglich trainieren muss, um eine Gewohnheit zu entwickeln.", "B. Dass Sporttermine die gleiche Priorität wie berufliche Termine haben sollten.", "C. Dass man die Intensität des Trainings ständig steigern muss."], richtig: 1, begruendung: "Text: '...als wären es wichtige Geschäftstermine.'" },
                    { frage: "3. Warum geben viele Menschen im März wieder auf?", antworten: ["A. Weil sie ihre Motivation durch zu hohe Erwartungen verloren haben.", "B. Weil die Fitnessstudios im Frühjahr oft zu voll sind.", "C. Weil sie keine Zeit mehr für ihre Geschäftstermine haben."], richtig: 0, begruendung: "Text: 'Wer sich unrealistische Ziele setzt, verliert schnell die Lust.'" }
                ]
            },
            {
                teilName: "Teil 1 - Text 2: Die Zukunft der Zeitung",
                audioSrc: "audio/de2-teil1-text2.mp3",
                transcript: "Wird die gedruckte Zeitung verschwinden? Während die junge Generation Nachrichten fast ausschließlich über soziale Medien konsumiert, schätzen ältere Leser immer noch das haptische Erlebnis von Papier. Doch der Trend geht eindeutig zum digitalen Abonnement. Verlage investieren kaum noch in teure Druckmaschinen, sondern in interaktive Apps. Das bedeutet jedoch nicht das Ende des Qualitätsjournalismus, sondern lediglich einen Wechsel des Mediums.",
                fragen: [
                    { frage: "4. Wie konsumieren junge Menschen heute meistens Nachrichten?", antworten: ["A. Durch das Lesen von gedruckten Tageszeitungen.", "B. Über digitale Plattformen und Netzwerke.", "C. Gar nicht, da sie kein Interesse an Nachrichten haben."], richtig: 1, begruendung: "Text: '...fast ausschließlich über soziale Medien konsumiert.'" },
                    { frage: "5. Was ist die aktuelle Strategie der Zeitungsverlage?", antworten: ["A. Sie versuchen, das haptische Erlebnis von Papier zu verbessern.", "B. Sie konzentrieren ihre Investitionen auf digitale Angebote.", "C. Sie stellen den Qualitätsjournalismus komplett ein."], richtig: 1, begruendung: "Text: 'Verlage investieren... in interaktive Apps.'" },
                    { frage: "6. Was sagt der Sprecher über die Zukunft des Journalismus?", antworten: ["A. Mit dem Ende des Papiers endet auch die Qualität der Nachrichten.", "B. Nur die Art und Weise der Verbreitung von Nachrichten ändert sich.", "C. Digitale Abonnements sind für die Verlage nicht rentabel."], richtig: 1, begruendung: "Text: '...lediglich einen Wechsel des Mediums.'" }
                ]
            },
            {
                teilName: "Teil 1 - Text 3: Workation",
                audioSrc: "audio/de2-teil1-text3.mp3",
                transcript: "Haben Sie schon einmal von 'Workation' gehört? Das Wort setzt sich aus 'Work' und 'Vacation' zusammen. Immer mehr Arbeitgeber erlauben es ihren Angestellten, den Laptop für ein paar Wochen am Strand von Mallorca oder in einer Berghütte in den Alpen aufzuklappen. Klingt traumhaft, oder? Doch Vorsicht: Wer glaubt, man könne den ganzen Tag im Pool liegen und nebenbei ein paar E-Mails beantworten, der irrt sich gewaltig. Die Erwartungen der Firmen an die Erreichbarkeit und die Qualität der Ergebnisse bleiben identisch zum Büroalltag. Oft führt die fehlende Trennung von Arbeitsplatz und Erholungsort sogar dazu, dass Mitarbeiter abends länger sitzen bleiben, weil das schlechte Gewissen plagt, dass man ja eigentlich 'im Urlaub' ist. Experten raten daher zu einer strikten Zeiteinteilung, damit die Workation nicht im Burnout endet.",
                fragen: [
                    { frage: "7. Was ist das Hauptmerkmal einer „Workation“?", antworten: ["A. Dass man während des Urlaubs überhaupt nicht arbeiten muss.", "B. Dass man seinen gewöhnlichen Arbeitsort vorübergehend an einen Urlaubsort verlegt.", "C. Dass der Arbeitgeber die Reisekosten komplett übernimmt."], richtig: 1, begruendung: "Text: '...den Laptop für ein paar Wochen am Strand... aufzuklappen.'" },
                    { frage: "8. Welches Problem wird im Text im Zusammenhang mit Workation genannt?", antworten: ["A. Die Internetverbindung an Urlaubsorten ist oft zu schwach...", "B. Die psychische Belastung steigt, da man Berufliches und Privates kaum noch trennen kann.", "C. Die meisten Mitarbeiter sind am Strand weniger produktiv..."], richtig: 1, begruendung: "Text: '...fehlende Trennung von Arbeitsplatz und Erholungsort...'" },
                    { frage: "9. Was empfiehlt der Text für eine gelungene Workation?", antworten: ["A. Dass man nur E-Mails bearbeitet...", "B. Dass man den Aufenthalt auf maximal eine Woche begrenzt.", "C. Dass man sich klare Arbeitszeiten setzt, um echte Erholung zu ermöglichen."], richtig: 2, begruendung: "Text: 'Experten raten daher zu einer strikten Zeiteinteilung...'" }
                ]
            },
            {
                teilName: "Teil 1 - Text 4: Second Hand",
                audioSrc: "audio/de2-teil1-text4.mp3",
                transcript: "Früher galt gebrauchte Kleidung als etwas für Leute mit wenig Geld. Heute ist der Kauf von Second-Hand-Mode ein echtes Lifestyle-Statement geworden. Vor allem die junge Generation möchte sich vom 'Fast Fashion'-Trend distanzieren, bei dem billige Kleidung unter fragwürdigen Bedingungen produziert und nach dreimaligem Tragen weggeworfen wird. Doch der Boom hat auch Schattenseiten: Auf Online-Plattformen für gebrauchte Mode beobachten wir eine zunehmende Kommerzialisierung. Viele Nutzer kaufen billige Neuware bei Discountern auf, um sie dann als 'Vintage' teurer weiterzuverkaufen. Der eigentliche ökologische Gedanke – nämlich Ressourcen zu schonen, indem man Dingen ein zweites Leben schenkt – tritt dabei oft in den Hintergrund. Wer wirklich nachhaltig handeln will, sollte daher eher lokale Tauschbörsen oder klassische Flohmärkte besuchen.",
                fragen: [
                    { frage: "10. Warum ist Second-Hand-Mode heute so beliebt?", antworten: ["A. Weil neue Kleidung extrem teuer geworden ist.", "B. Weil viele Menschen ein Zeichen gegen die Wegwerfgesellschaft setzen wollen.", "C. Weil Vintage-Kleidung qualitativ hochwertiger ist..."], richtig: 1, begruendung: "Text: '...möchte sich vom Fast Fashion-Trend distanzieren...'" },
                    { frage: "11. Welche negative Entwicklung wird auf Online-Plattformen beobachtet?", antworten: ["A. Es gibt dort kaum noch attraktive Kleidung...", "B. Die Preise für echte Vintage-Stücke sind drastisch gesunken.", "C. Händler nutzen die Plattformen aus, um billige Neuware gewinnbringend zu verkaufen."], richtig: 2, begruendung: "Text: 'Viele Nutzer kaufen billige Neuware... um sie dann als Vintage teurer weiterzuverkaufen.'" },
                    { frage: "12. Wo findet man laut Sprecher die ehrlichste Form der Nachhaltigkeit?", antworten: ["A. In exklusiven Boutiquen...", "B. Bei regionalen Veranstaltungen, wo Kleidung direkt getauscht oder verkauft wird.", "C. In den großen Online-Shops..."], richtig: 1, begruendung: "Text: '...lokale Tauschbörsen oder klassische Flohmärkte besuchen.'" }
                ]
            },
            {
                teilName: "Teil 1 - Text 5: Insekten auf dem Teller",
                audioSrc: "audio/de2-teil1-text5.mp3",
                transcript: "In vielen Kulturen gehören sie schon lange zum Speiseplan, bei uns rufen sie meistens noch Ekel hervor: Insekten. Dabei sind Grillen, Heuschrecken und Mehlwürmer wahre Superfoods. Sie enthalten fast so viel Protein wie Rindfleisch, benötigen aber bei der Zucht nur einen Bruchteil des Wassers und der Landfläche. Zudem stoßen sie kaum Treibhausgase aus. Die EU hat mittlerweile die ersten Insektenarten als Lebensmittel zugelassen. Doch die Lebensmittelindustrie weiß, dass die Hemmschwelle der Verbraucher groß ist. Deshalb werden Insekten oft nicht im Ganzen serviert, sondern zu Mehl verarbeitet, das man in Nudeln, Riegeln oder Brot verstecken kann. So merkt der Kunde gar nicht, dass er nachhaltiges Protein konsumiert. Experten sind sicher: In zehn Jahren wird der Anblick von Insektenprodukten im Supermarktregal so normal sein wie heute der von Tofu.",
                fragen: [
                    { frage: "13. Welchen ökologischen Vorteil haben Insekten gegenüber Rindfleisch?", antworten: ["A. Sie produzieren bei der Verarbeitung keine Abfälle.", "B. Sie benötigen für die Aufzucht deutlich weniger natürliche Ressourcen wie Wasser.", "C. Sie können überall auf der Welt ohne spezielle Ställe gezüchtet werden."], richtig: 1, begruendung: "Text: '...benötigen aber bei der Zucht nur einen Bruchteil des Wassers und der Landfläche.'" },
                    { frage: "14. Wie versucht die Industrie, die Vorurteile der Kunden zu überwinden?", antworten: ["A. Durch intensive Werbekampagnen...", "B. Indem sie Insektenprotein in bereits bekannten Lebensmitteln verarbeitet.", "C. Indem sie Insektenprodukte besonders günstig anbietet."], richtig: 1, begruendung: "Text: '...zu Mehl verarbeitet, das man in Nudeln, Riegeln oder Brot verstecken kann.'" },
                    { frage: "15. Was prognostiziert der Text für die Zukunft der Ernährung?", antworten: ["A. Insekten werden Fleisch komplett ersetzen.", "B. Insektenprodukte werden ein fester und gewöhnlicher Bestandteil unseres Sortiments sein.", "C. Die EU wird bald alle Fleischprodukte verbieten."], richtig: 1, begruendung: "Text: 'In zehn Jahren wird der Anblick von Insektenprodukten... so normal sein wie heute der von Tofu.'" }
                ]
            },
            {
                teilName: "Teil 2: Warten ist reine Kopfsache",
                audioSrc: "audio/de2-teil2.mp3",
                transcript: "Guten Tag! Haben Sie sich schon einmal gefragt, warum fünf Minuten an einer roten Ampel sich wie eine Ewigkeit anfühlen, während fünf Minuten bei einem guten Gespräch wie im Flug vergehen? In der Verhaltensökonomie wissen wir: Warten ist reine Kopfsache. Es ist nicht die Uhr, die uns stresst, sondern das Gefühl der verlorenen, ungenutzten Zeit. Ein berühmtes Beispiel aus der Architekturpsychologie zeigt dies deutlich: In einem New Yorker Hochhaus beschwerten sich die Mieter über die extrem langsamen Aufzüge. Anstatt Millionen in neue Motoren zu investieren, installierte man Spiegel neben den Türen. Das Ergebnis? Die Beschwerden hörten sofort auf. Nicht, weil die Aufzüge schneller wurden, sondern weil die Menschen beschäftigt waren, ihr Aussehen zu prüfen. Die Ablenkung veränderte die Zeitwahrnehmung. Ein weiteres Phänomen ist die 'Gerechtigkeit' in der Schlange. Wir hassen es, wenn die Nebenschlange schneller voranzukommen scheint. Statistisch gesehen ist das oft gar nicht der Fall, aber unser Gehirn ist auf das Negative programmiert. Wir erinnern uns an das eine Mal, wenn wir Pech hatten, aber vergessen die zehn Male, in denen wir die schnellste Kasse gewählt haben. Für Unternehmen ist heute die 'Transparenz' der Schlüssel. Nichts ist schlimmer als eine Warteschleife am Telefon ohne Information. Sobald man uns sagt: 'Es gibt eine technische Störung, wir sind in drei Minuten für Sie da', sinkt unser Blutdruck. Das Ungewisse ist der Feind der Geduld. Wenn wir verstehen, warum wir warten, akzeptieren wir es eher. Zusammenfassend lässt sich sagen: Ein intelligentes Wartemanagement geht nicht nur darum, mehr Kassen zu öffnen. Es geht darum, die psychische Leere des Wartens zu füllen.",
                fragen: [
                    { frage: "16. Was ist laut Dr. Falk das Hauptproblem beim Warten?", antworten: ["A. Die tatsächliche Zeit.", "B. Die subjektive Wahrnehmung der Zeit, die durch Langeweile negativ beeinflusst wird.", "C. Dass wir oft unfreundliche Menschen treffen."], richtig: 1, begruendung: "Text: 'Es ist nicht die Uhr, die uns stresst, sondern das Gefühl der verlorenen, ungenutzten Zeit.'" },
                    { frage: "17. Welchen Effekt haben Spiegel in der Nähe von Aufzügen?", antworten: ["A. Raum wirkt größer.", "B. Sie lenken die Wartenden ab und lassen die Zeit gefühlt schneller vergehen.", "C. Dienen der Sicherheit."], richtig: 1, begruendung: "Text: 'Die Ablenkung veränderte die Zeitwahrnehmung.'" },
                    { frage: "18. Warum empfinden wir die Schlange neben uns oft als „schneller“?", antworten: ["A. Effizientere Mitarbeiter.", "B. Wegen einer psychologischen Verzerrung: Wir merken uns nur die Momente, in denen wir blockiert sind.", "C. Weniger Produkte im Wagen."], richtig: 1, begruendung: "Text: '...unser Gehirn ist auf das Negative programmiert.'" },
                    { frage: "19. Was versteht man unter dem „Pionier-Effekt“ beim Warten?", antworten: ["A. Größter Stress an der Spitze.", "B. Dass das Gefühl, Fortschritte zu machen, wichtiger ist als die absolute Dauer.", "C. Leere Schlangen bevorzugen."], richtig: 1, begruendung: "Dựa theo bối cảnh bài nói về cảm giác tiến triển." },
                    { frage: "20. Wie beeinflusst die Transparenz den Wartprozess?", antworten: ["A. Wenn Kunden den Grund für eine Verzögerung kennen, steigt ihre Geduld.", "B. Zu viel Information führt zu Aggressionen.", "C. Langsameres Arbeiten."], richtig: 0, begruendung: "Text: 'Wenn wir verstehen, warum wir warten, akzeptieren wir es eher.'" },
                    { frage: "21. Welches Fazit zieht Dr. Falk für Unternehmen?", antworten: ["A. Wartezeit auf Null reduzieren.", "B. Das Management der Erwartungen ist wichtiger als die physische Verkürzung der Schlange.", "C. Kunden entschädigen."], richtig: 1, begruendung: "Text: 'Es geht darum, die psychische Leere des Wartens zu füllen.'" }
                ]
            },
            {
                teilName: "Teil 3: Bürohunde",
                audioSrc: "audio/de2-teil3.mp3",
                transcript: "Frau Wagner: ... Das Thema „Bürohunde“ spaltet die Gemüter. Frau Jung, warum ist das eine Bereicherung?\nFrau Jung: ... es ist wissenschaftlich belegt, dass die Interaktion mit Hunden den Cortisolspiegel senkt. Er ist unser vierbeiniger Feel-Good-Manager. Außerdem bricht er das Eis... Das stärkt den Zusammenhalt enorm.\nHerr Koch: ... Aber als Abteilungsleiter muss ich auch die andere Seite sehen. Mitarbeiter, die panische Angst vor Hunden haben oder unter schweren Allergien leiden. Für die wird der Arbeitsplatz zur Qual. Zudem darf man den Zeitfaktor nicht vergessen: Jedes Mal, wenn der Hund bellt... wird die Konzentration unterbrochen.\nFrau Jung: Natürlich braucht es eine strikte „Hunde-Etikette“... Für viele junge Bewerber ist die Erlaubnis, den Hund mitzubringen, heute sogar ein entscheidender Grund, sich für uns... zu entscheiden.\nHerr Koch: ... Was ist mit den Kollegen ohne Hund? Die fühlen sich vielleicht benachteiligt... Meiner Meinung nach eignet sich auch längst nicht jedes Großraumbüro für Tiere...\nFrau Jung: ... Eine Abstimmung im Team ist ein Muss. Wenn auch nur einer strikt dagegen ist, geht es eben nicht.\nHerr Koch: Einverstanden, Transparenz ist wichtig. Aber am Ende trägt der Arbeitgeber das Risiko...",
                fragen: [
                    { frage: "22. Die Anwesenheit von Tieren reduziert nachweislich das Stresslevel im Team.", antworten: ["Frau Wagner", "Herr Koch", "Frau Jung"], richtig: 2, begruendung: "Frau Jung: '...senkt den Cortisolspiegel.'" },
                    { frage: "23. Man muss Rücksicht auf Kollegen mit Allergien oder Ängsten nehmen.", antworten: ["Frau Wagner", "Herr Koch", "Frau Jung"], richtig: 1, begruendung: "Herr Koch: '...panische Angst vor Hunden haben oder unter schweren Allergien leiden.'" },
                    { frage: "24. Ein Hund im Büro führt zu ständigen Unterbrechungen der Arbeitsabläufe.", antworten: ["Frau Wagner", "Herr Koch", "Frau Jung"], richtig: 1, begruendung: "Herr Koch: '...wird die Konzentration unterbrochen.'" },
                    { frage: "25. Klare Regeln und eine „Hunde-Etikette“ sind für den Erfolg entscheidend.", antworten: ["Frau Wagner", "Herr Koch", "Frau Jung"], richtig: 2, begruendung: "Frau Jung: 'Natürlich braucht es eine strikte Hunde-Etikette.'" },
                    { frage: "26. Die Attraktivität des Unternehmens für junge Talente steigt durch Haustiere.", antworten: ["Frau Wagner", "Herr Koch", "Frau Jung"], richtig: 2, begruendung: "Frau Jung: '...ein entscheidender Grund, sich für uns... zu entscheiden.'" },
                    { frage: "27. Tiere im Büro können das Betriebsklima und die Kommunikation verbessern.", antworten: ["Frau Wagner", "Herr Koch", "Frau Jung"], richtig: 2, begruendung: "Frau Jung: 'Außerdem bricht er das Eis...'" },
                    { frage: "28. Nicht jede Büroumgebung ist für die Haltung von Tieren geeignet.", antworten: ["Frau Wagner", "Herr Koch", "Frau Jung"], richtig: 1, begruendung: "Herr Koch: '...eignet sich auch längst nicht jedes Großraumbüro für Tiere...'" },
                    { frage: "29. Es ist ungerecht gegenüber Mitarbeitern, die keine Haustiere haben.", antworten: ["Frau Wagner", "Herr Koch", "Frau Jung"], richtig: 1, begruendung: "Herr Koch: 'Die fühlen sich vielleicht benachteiligt...'" },
                    { frage: "30. Die endgültige Entscheidung sollte immer beim gesamten Team liegen.", antworten: ["Frau Wagner", "Herr Koch", "Frau Jung"], richtig: 2, begruendung: "Frau Jung: 'Eine Abstimmung im Team ist ein Muss.'" }
                ]
            },
            {
                teilName: "Teil 4: Der Vortrag (Kaffee)",
                audioSrc: "audio/de2-teil4.mp3",
                transcript: "Guten Tag! Kaffee ist für viele von uns das erste Ritual des Tages. Doch hinter der Tasse in Ihrer Hand steckt eine jahrhundertelange Reise. Ursprünglich entdeckten Mönche in Äthiopien, dass sie durch die Beeren der Kaffeepflanze bei ihren langen Gebeten die Müdigkeit besiegen konnten. Von dort eroberte der Kaffee die Welt. Im 17. Jahrhundert entstanden in London und Paris die ersten Kaffeehäuser. Sie waren weit mehr als Gaststätten; sie waren die 'Internet-Cafés' der Aufklärung. Hier wurden Geschäfte besiegelt und politische Diskurse geführt. Heute befinden wir uns in der 'Third Wave'. Kaffee ist kein anonymes Pulver mehr. Wir wollen wissen: Von welcher Farm kommt die Bohne? Wie wurde sie geröstet? Kaffee ist zum Genussobjekt geworden, vergleichbar mit edlem Wein. Doch über dieser Kultur hängt ein dunkler Schatten: der Klimawandel. Die Arabica-Bohne ist extrem empfindlich. Sie braucht kühle Nächte und spezifische Höhenlagen. Steigen die Temperaturen nur um zwei Grad, verschieben sich die fruchtbaren Zonen weiter nach oben – dort, wo oft geschützte Bergwälder liegen. Die ökologische Herausforderung ist gewaltig. Zudem kämpfen viele der 25 Millionen Kaffeebauern weltweit um ihre Existenz. Der Weltmarktpreis für Rohkaffee ist extrem volatil. Hier setzt der faire Handel an, der den Bauern Mindestpreise garantiert, unabhängig von den Börsenschwankungen. Was bringt die Zukunft? Wir sehen einen Trend zum 'Direct Trade'. Kleine Röstereien umgehen die großen Börsen und verhandeln direkt mit den Kooperativen vor Ort. Das sorgt für Transparenz und Qualität. Für uns Konsumenten bedeutet das aber auch: Der Preis für das tägliche Vergnügen wird steigen. Kaffee wird in den nächsten Jahrzehnten wohl wieder das werden, was er am Anfang war: ein kostbares Gut für besondere Momente.",
                fragen: [
                    { frage: "31. Was war die ursprüngliche Funktion von Kaffee in seiner frühen Geschichte?", antworten: ["A. Exportgut.", "B. Er diente religiösen Gruppen dazu, bei nächtlichen Gebeten wach zu bleiben.", "C. Luxusgetränk an Königshöfen."], richtig: 1, begruendung: "Text: '...bei ihren langen Gebeten die Müdigkeit besiegen konnten.'" },
                    { frage: "32. Wie veränderte sich die Bedeutung des Kaffees durch die ersten Kaffeehäuser?", antworten: ["A. Symbol für Revolutionen.", "B. Kaffeehäuser wurden zu zentralen Orten für den Austausch von Nachrichten und Ideen.", "C. Ersatz für schlechtes Wasser."], richtig: 1, begruendung: "Text: '...sie waren die Internet-Cafés der Aufklärung.'" },
                    { frage: "33. Was kennzeichnet die sogenannte „Third Wave of Coffee“?", antworten: ["A. Massenproduktion.", "B. Der Fokus auf die individuelle Herkunft der Bohne und handwerkliche Röstung.", "C. Kaffeekapseln."], richtig: 1, begruendung: "Text: 'Wir wollen wissen: Von welcher Farm kommt die Bohne? Wie wurde sie geröstet?'" },
                    { frage: "34. Welches ökologische Problem wird im Zusammenhang mit dem Kaffeeanbau genannt?", antworten: ["A. Verbraucht zu viel Wasser.", "B. Für neue Plantagen werden oft wertvolle Waldflächen gerodet.", "C. Entzieht dem Boden Mineralien."], richtig: 1, begruendung: "Text: '...verschieben sich die fruchtbaren Zonen weiter nach oben – dort, wo oft geschützte Bergwälder liegen.'" },
                    { frage: "35. Wie wirkt sich der Klimawandel direkt auf die Kaffeebauern aus?", antworten: ["A. Ernten zerstört durch Regen.", "B. Die Anbaugebiete für die hochwertige Arabica-Bohne schrumpfen aufgrund steigender Temperaturen.", "C. Pflanzen produzieren weniger Koffein."], richtig: 1, begruendung: "Text: 'Steigen die Temperaturen nur um zwei Grad, verschieben sich die fruchtbaren Zonen...'" },
                    { frage: "36. Warum ist fairer Handel (Fair Trade) beim Kaffee besonders wichtig?", antworten: ["A. Stabile Qualität.", "B. Damit die Kleinbauern trotz schwankender Weltmarktpreise ein gesichertes Einkommen haben.", "C. Höhere Steuern."], richtig: 1, begruendung: "Text: '...der den Bauern Mindestpreise garantiert, unabhängig von den Börsenschwankungen.'" },
                    { frage: "37. Was ist eine neue technologische Entwicklung in der Kaffeeproduktion?", antworten: ["A. Die Ernte durch vollautomatische Roboter (allgemeiner Trend).", "B. Anbau in Europa.", "C. Genetische Veränderung."], richtig: 0, begruendung: "Câu hỏi mở rộng về xu hướng ngành (Direct Trade)." },
                    { frage: "38. Welchen Trend beobachtet man beim Konsumverhalten?", antworten: ["A. Keinen Kaffee mehr.", "B. Das Wissen über die Zubereitungsarten wird zu einem wichtigen Teil des Lifestyles.", "C. Nur als Wachmacher."], richtig: 1, begruendung: "Text: 'Kaffee ist zum Genussobjekt geworden...'" },
                    { frage: "39. Was versteht man unter „Direktimport“ (Direct Trade)?", antworten: ["A. Dass der Kaffee ohne Zwischenhändler direkt vom Bauern gekauft wird.", "B. Transport mit Flugzeug.", "C. Kunde holt in Fabrik ab."], richtig: 0, begruendung: "Text: 'Kleine Röstereien umgehen die großen Börsen und verhandeln direkt mit den Kooperativen vor Ort.'" },
                    { frage: "40. Welches Fazit zieht der Sprecher über die Zukunft des Kaffees?", antworten: ["A. Billiges Massenprodukt.", "B. Der Genuss von hochwertigem Kaffee wird aufgrund des Klimawandels teurer und exklusiver.", "C. Verlagerung in Laboratorien."], richtig: 1, begruendung: "Text: 'Der Preis für das tägliche Vergnügen wird steigen. Kaffee wird... ein kostbares Gut für besondere Momente.'" }
                ]
            }
        ]
    }
];
