const alleHoerenPruefungen = [
    {
        id: 1,
        niveau: "B2",
        name: "Đề 1: Gesellschaft & Wirtschaft (Goethe B2)",
        teile: [
            {
                teilName: "Teil 1 - Text 1: Die Renaissance des Handwerks",
                audioSrc: "audio/de1-teil1-text1.mp3",
                transcript: `Lange Zeit galt eine akademische Ausbildung als das Nonplusultra für eine erfolgreiche Karriere. Doch das Blatt wendet sich. Angesichts überfüllter Hörsäle und einer wachsenden Zahl an Absolventen in Geisteswissenschaften, die prekäre Beschäftigungsverhältnisse vorfinden, rückt das Handwerk wieder in den Fokus. Entgegen dem Klischee von schwerer körperlicher Arbeit bei geringem Lohn, bietet der Sektor heute dank Digitalisierung und Smart-Home-Technologien hochkomplexe Aufgabenbereiche. Die Vergütung für spezialisierte Fachkräfte übersteigt mittlerweile oft das Einstiegsgehalt von Master-Absolventen. Dennoch bleibt der Nachwuchsmangel bestehen, da das gesellschaftliche Ansehen der praktischen Arbeit nur zögerlich dem finanziellen Anreiz folgt.`,
                fragen: [
                    { frage: "1. Warum entscheiden sich wieder mehr Menschen für eine handwerkliche Ausbildung?", antworten: ["A. Weil ein Studium heute keine Garantie mehr für eine stabile Anstellung ist.", "B. Weil die Arbeit im Handwerk körperlich weniger anstrengend geworden ist als früher.", "C. Weil die Hörsäle an den Universitäten aus Sicherheitsgründen geschlossen wurden."], richtig: 0, begruendung: "Text: 'Angesichts überfüllter Hörsäle und Absolventen, die prekäre Beschäftigungsverhältnisse vorfinden, rückt das Handwerk wieder in den Fokus.'" },
                    { frage: "2. Was sagt der Text über die Bezahlung im Handwerk aus?", antworten: ["A. Sie ist immer noch niedriger als in akademischen Berufen.", "B. Spezialisierte Handwerker verdienen oft mehr als Berufseinsteiger mit Universitätsabschluss.", "C. Die Löhne sind nur gestiegen, weil die Digitalisierung Kosten spart."], richtig: 1, begruendung: "Text: 'Die Vergütung für spezialisierte Fachkräfte übersteigt mittlerweile oft das Einstiegsgehalt von Master-Absolventen.'" },
                    { frage: "3. Was ist das Hauptproblem für die Zukunft des Sektors?", antworten: ["A. Dass die Digitalisierung viele Arbeitsplätze überflüssig macht.", "B. Dass junge Menschen das Image des Handwerks skeptisch sehen.", "C. Dass es zu viele staatliche Förderungen gibt."], richtig: 1, begruendung: "Text: 'Dennoch bleibt der Nachwuchsmangel bestehen, da das gesellschaftliche Ansehen der praktischen Arbeit nur zögerlich dem finanziellen Anreiz folgt.'" }
                ]
            },
            {
                teilName: "Teil 1 - Text 2: Greenwashing",
                audioSrc: "audio/de1-teil1-text2.mp3",
                transcript: `Wer heute einkauft, trifft auf ein Meer von 'Öko'-Labeln. Doch Vorsicht ist geboten: Der Begriff 'klimaneutral' ist gesetzlich kaum geschützt. Viele Konzerne investieren lieber in Marketingkampagnen und den Kauf von zweifelhaften CO2-Zertifikaten, statt ihre Produktionsketten tatsächlich umzustrukturieren. Für den Verbraucher ist es fast unmöglich, echte Nachhaltigkeit von geschickter PR zu unterscheiden. Experten fordern daher eine strengere Zertifizierungspflicht durch unabhängige staatliche Organe, um die inflationäre Verwendung von Umweltversprechen einzudämmen. Solange dies nicht geschieht, bleibt der Griff zum 'grünen' Produkt oft eine reine Gewissensberuhigung ohne ökologischen Mehrwert.`,
                fragen: [
                    { frage: "4. Was kritisiert der Text am Begriff „klimaneutral“?", antworten: ["A. Nur für Schwerindustrie verwendet.", "B. Dass die gesetzlichen Regelungen für seine Verwendung unzureichend sind.", "C. Verbraucher ignorieren den Begriff."], richtig: 1, begruendung: "Text: 'Der Begriff klimaneutral ist gesetzlich kaum geschützt.'" },
                    { frage: "5. Wie gehen viele Konzerne mit dem Thema Nachhaltigkeit um?", antworten: ["A. Sie verändern ihre gesamte Produktion.", "B. Sie setzen auf Werbung und Ausgleichszahlungen statt auf reale Veränderungen.", "C. Arbeiten mit staatlichen Organen zusammen."], richtig: 1, begruendung: "Text: 'Viele Konzerne investieren lieber in Marketingkampagnen und den Kauf von zweifelhaften CO2-Zertifikaten...'" },
                    { frage: "6. Welche Lösung wird im Text vorgeschlagen?", antworten: ["A. Verbraucher sollen sich informieren.", "B. Preise drastisch erhöhen.", "C. Eine verpflichtende Überprüfung durch neutrale Instanzen muss eingeführt werden."], richtig: 2, begruendung: "Text: 'Experten fordern daher eine strengere Zertifizierungspflicht durch unabhängige staatliche Organe...'" }
                ]
            },
            {
                teilName: "Teil 1 - Text 3: Das Ende des Bargelds?",
                audioSrc: "audio/de1-teil1-text3.mp3",
                transcript: `In skandinavischen Ländern ist es bereits Alltag, in Deutschland hingegen ein hochemotionales Thema: Die Abschaffung des Bargelds. Befürworter verweisen auf die Effizienz und die Bekämpfung von Schwarzarbeit. Kritiker jedoch sehen im Verschwinden von Münzen und Scheinen den Weg in den 'gläsernen Bürger'. Jede Transaktion hinterlässt eine digitale Spur, die von Banken und potenziell auch vom Staat ausgewertet werden kann. Zudem warnt der Einzelhandelsverband vor einer sozialen Ausgrenzung älterer Generationen, für die digitale Bezahlsysteme oft eine unüberwindbare Barriere darstellen. Die Debatte zeigt: Es geht um weit mehr als nur um Bequemlichkeit beim Bezahlen.`,
                fragen: [
                    { frage: "7. Welchen Vorteil nennen die Befürworter der bargeldlosen Gesellschaft?", antworten: ["A. Förderung der Anonymität.", "B. Eine effektivere Kontrolle von illegalen Beschäftigungsverhältnissen.", "C. Einfacher für ältere Menschen."], richtig: 1, begruendung: "Text: 'Befürworter verweisen auf die Effizienz und die Bekämpfung von Schwarzarbeit.'" },
                    { frage: "8. Was ist die größte Sorge der Kritiker?", antworten: ["A. Zu hohe Gebühren.", "B. Dass der Datenschutz verloren geht und das Finanzverhalten überwachbar wird.", "C. Technik bei Stromausfall."], richtig: 1, begruendung: "Text: 'Kritiker jedoch sehen im Verschwinden von Münzen und Scheinen den Weg in den gläsernen Bürger.'" },
                    { frage: "9. Warum warnt der Einzelhandelsverband vor der Umstellung?", antworten: ["A. Weniger Gewinn.", "B. Weil bestimmte Bevölkerungsgruppen vom wirtschaftlichen Leben abgeschnitten werden könnten.", "C. Fehlende Infrastruktur."], richtig: 1, begruendung: "Text: 'Zudem warnt der Einzelhandelsverband vor einer sozialen Ausgrenzung älterer Generationen...'" }
                ]
            },
            {
                teilName: "Teil 1 - Text 4: Urban Farming",
                audioSrc: "audio/de1-teil1-text4.mp3",
                transcript: `Die Idee, Gemüse direkt auf den Dächern von Hochhäusern anzubauen, klingt nach einer ökologischen Revolution. Doch bei näherer Betrachtung der Energiebilanz schwindet die Euphorie oft. Während der Transportweg zwar entfällt, ist der Ressourcenverbrauch für Bewässerungssysteme und künstliche Beleuchtung in geschlossenen Räumen, dem sogenannten 'Vertical Farming', enorm. Ökonomen betonen, dass diese Methode derzeit nur für hochpreisige Nischenprodukte wie exotische Kräuter rentabel ist. Für die Grundversorgung der städtischen Bevölkerung mit Weizen oder Kartoffeln bleibt die traditionelle Landwirtschaft auf dem Land vorerst unersetzlich, da die Kosten pro Quadratmeter in der Innenstadt schlichtweg zu hoch kalkuliert sind.`,
                fragen: [
                    { frage: "10. Warum ist die Energiebilanz von Urban Farming oft negativ?", antworten: ["A. Transport verbraucht Treibstoff.", "B. Weil die technische Instandhaltung der Anlagen extrem viel Energie benötigt.", "C. Bauern nutzen effizientere Traktoren."], richtig: 1, begruendung: "Text: '...ist der Ressourcenverbrauch für Bewässerungssysteme und künstliche Beleuchtung in geschlossenen Räumen enorm.'" },
                    { frage: "11. Für welche Produkte eignet sich Vertical Farming momentan am ehesten?", antworten: ["A. Preisgünstige Grundnahrungsmittel.", "B. Für spezielle Produkte, die zu einem hohen Preis verkauft werden können.", "C. Obstsorten."], richtig: 1, begruendung: "Text: '...derzeit nur für hochpreisige Nischenprodukte wie exotische Kräuter rentabel ist.'" },
                    { frage: "12. Was ist das größte Hindernis für großflächigen Anbau in Städten?", antworten: ["A. Mangel an Fachkräften.", "B. Die hohen finanziellen Belastungen durch die Immobilienpreise in der Stadt.", "C. Widerstand der Landwirte."], richtig: 1, begruendung: "Text: '...da die Kosten pro Quadratmeter in der Innenstadt schlichtweg zu hoch kalkuliert sind.'" }
                ]
            },
            {
                teilName: "Teil 1 - Text 5: Lebenslanges Lernen",
                audioSrc: "audio/de1-teil1-text5.mp3",
                transcript: `In einer sich rasant wandelnden Arbeitswelt verliert das einmal erworbene Diplom immer schneller an Wert. Das Konzept des 'lebenslangen Lernens' ist daher kein bloßes Schlagwort mehr, sondern eine Überlebensstrategie. Doch die Verantwortung dafür wird zunehmend auf das Individuum abgewälzt. Während Unternehmen früher interne Fortbildungen finanzierten, wird heute oft erwartet, dass Arbeitnehmer sich in ihrer Freizeit und auf eigene Kosten qualifizieren. Experten warnen vor einer 'Bildungsschere': Wer bereits gut verdient und Zeit hat, investiert in Wissen, während Geringverdiener in ihren veralteten Berufsfeldern gefangen bleiben. Staatliche Bildungsurlaube könnten hier ein Korrektiv sein, werden aber bisher kaum in Anspruch genommen.`,
                fragen: [
                    { frage: "13. Wie hat sich die Bedeutung von Bildungsabschlüssen verändert?", antworten: ["A. Ein Diplom garantiert lebenslange Sicherheit.", "B. Das Wissen aus der Ausbildung veraltet heute wesentlich schneller als früher.", "C. Universitätsabschlüsse sind wertvoller."], richtig: 1, begruendung: "Text: 'In einer sich rasant wandelnden Arbeitswelt verliert das einmal erworbene Diplom immer schneller an Wert.'" },
                    { frage: "14. Was wird an der aktuellen Praxis der Weiterbildung kritisiert?", antworten: ["A. Zu viele Fortbildungen.", "B. Dass die Kosten und der Zeitaufwand immer häufiger bei den Angestellten liegen.", "C. Keine staatlichen Angebote."], richtig: 1, begruendung: "Text: '...wird heute oft erwartet, dass Arbeitnehmer sich in ihrer Freizeit und auf eigene Kosten qualifizieren.'" },
                    { frage: "15. Was ist das Risiko der beschriebenen „Bildungsschere“?", antworten: ["A. Dass Menschen mit geringem Einkommen den Anschluss am Arbeitsmarkt verlieren.", "B. Dass gut verdienende Arbeitnehmer nur noch lernen.", "C. Qualität der Lehre sinkt."], richtig: 0, begruendung: "Text: '...während Geringverdiener in ihren veralteten Berufsfeldern gefangen bleiben.'" }
                ]
            },
            {
                teilName: "Teil 2: Der Experten-Vortrag (Umgang mit dem Scheitern)",
                audioSrc: "audio/de1-teil2.mp3",
                transcript: `Guten Tag, meine Damen und Herren. In der heutigen Start-up-Welt wird oft das Bild des perfekten Gründers gezeichnet. Doch die Realität sieht anders aus: Über 80 % aller Neugründungen scheitern in den ersten drei Jahren. Warum ist das so?
Ein wesentlicher Aspekt ist die kulturelle Prägung. Während man in den USA ein gescheitertes Projekt oft als 'notwendige Erfahrung' im Lebenslauf verbucht, herrscht in Europa – und besonders im deutschsprachigen Raum – eine regelrechte Stigmatisierung vor. Das Problem ist hier weniger der Zugang zu Kapital, sondern die Tatsache, dass der gesellschaftliche Status extrem eng mit einer lückenlosen Erfolgsbiografie verknüpft ist. Wer einmal scheitert, gilt oft als 'beschädigt', was psychologisch einen enormen Druck aufbaut.
Was wir also brauchen, ist eine 'positive Fehlerkultur'. Das bedeutet ausdrücklich nicht, dass wir Nachlässigkeit fördern oder Fehler feiern sollen. Vielmehr geht es darum, eine Umgebung zu schaffen, in der Missgeschicke nicht vertuscht, sondern transparent analysiert werden. Nur so lassen sich Defizite im System – und nicht nur beim Individuum – identifizieren.
Ein klassischer Fehler, den ich immer wieder beobachte, ist die sogenannte 'Eskalation des Commitments'. Viele Gründer verlieben sich so sehr in ihre Vision, dass sie Warnsignale des Marktes ignorieren. Sie verbrennen Kapital für ein Produkt, das eigentlich niemand braucht, anstatt frühzeitig den Kurs zu ändern. Hier bietet die Digitalisierung heute enorme Chancen: Dank Echtzeit-Datenanalysen lassen sich Fehlentwicklungen beinahe sofort erkennen und korrigieren, bevor sie existenzbedrohend werden.
Für etablierte Großkonzerne ist dies oft schwierig, da ihre starren Hierarchien Innovationen hemmen. Mein Rat an diese Firmen: Schaffen Sie geschützte Räume, kleine 'Experimentier-Inseln', in denen Teams völlig autark wie junge Start-ups agieren können, ohne den Ballast der Konzernverwaltung.
Lassen Sie mich zum Schluss eines betonen: Scheitern an sich ist kein Verdienst. Es wird erst dann zu einem Mehrwert für die Karriere oder das Unternehmen, wenn man die intellektuelle Disziplin besitzt, die Ursachen schonungslos aufzuarbeiten. Ohne Reflexion ist ein Misserfolg schlichtweg nur verlorene Zeit.`,
                fragen: [
                    { frage: "16. Warum ist die „Fear of Failure“ in Europa ausgeprägter als in den USA?", antworten: ["A. Weniger staatliche Unterstützung.", "B. Weil das soziale Ansehen in Europa stärker an beruflichen Erfolg gekoppelt ist.", "C. Schwerere Kreditvergabe."], richtig: 1, begruendung: "Vortrag: '...die Tatsache, dass der gesellschaftliche Status extrem eng mit einer lückenlosen Erfolgsbiografie verknüpft ist.'" },
                    { frage: "17. Was versteht der Redner unter einer „positiven Fehlerkultur“?", antworten: ["A. Fehler absichtlich machen.", "B. Dass Misserfolge offen kommuniziert werden, um systemische Schwachstellen zu finden.", "C. Mitarbeiter nicht haftbar machen."], richtig: 1, begruendung: "Vortrag: '...eine Umgebung zu schaffen, in der Missgeschicke nicht vertuscht, sondern transparent analysiert werden.'" },
                    { frage: "18. Welchen Fehler machen viele Gründer laut dem Experten in der Anfangsphase?", antworten: ["A. Zu viel Geld in Marketing.", "B. Sie halten zu lange an einer ursprünglichen Idee fest, die am Markt vorbeigeht.", "C. Zu viele Mitarbeiter."], richtig: 1, begruendung: "Vortrag: 'Viele Gründer verlieben sich so sehr in ihre Vision, dass sie Warnsignale des Marktes ignorieren.'" },
                    { frage: "19. Wie beeinflusst die Digitalisierung den Umgang mit Fehlern?", antworten: ["A. Durch Datenanalysen können Fehlentscheidungen heute schneller korrigiert werden.", "B. Mitarbeiter verstecken Fehler.", "C. Größere Schäden."], richtig: 0, begruendung: "Vortrag: 'Dank Echtzeit-Datenanalysen lassen sich Fehlentwicklungen beinahe sofort erkennen...'" },
                    { frage: "20. Was empfiehlt der Experte etablierten Großunternehmen?", antworten: ["A. Fokus auf Tradition.", "B. Kleine, unabhängige Teams zu bilden, die wie Start-ups agieren dürfen.", "C. Hierarchien verstärken."], richtig: 1, begruendung: "Vortrag: 'Schaffen Sie geschützte Räume, kleine Experimentier-Inseln, in denen Teams völlig autark wie junge Start-ups agieren können...'" },
                    { frage: "21. Welches Fazit zieht der Redner am Ende seines Vortrags?", antworten: ["A. Dass Scheitern nur dann wertvoll ist, wenn eine tiefgreifende Analyse erfolgt.", "B. Jeder Gründer muss scheitern.", "C. Politik soll Risiken übernehmen."], richtig: 0, begruendung: "Vortrag: 'Es wird erst dann zu einem Mehrwert... wenn man die intellektuelle Disziplin besitzt, die Ursachen schonungslos aufzuarbeiten.'" }
                ]
            },
            {
                teilName: "Teil 3: Erweiterte Diskussion (Wer sagt was?)",
                audioSrc: "audio/de1-teil3.mp3",
                transcript: `Frau Weber: Guten Abend. In unserer heutigen Debatte geht es um das Ende einer Ära. Viele große Konzerne rufen ihre Belegschaft aus dem Homeoffice zurück in die Bürotürme. Frau Lange, Sie als Gründerin eines Software-Unternehmens halten das für einen Rückschritt, oder?
Frau Lange: Absolut. Wir befinden uns in einem globalen Wettbewerb um Fachkräfte. Wer heute von hochqualifizierten Programmierern verlangt, zwei Stunden täglich im Stau zu stehen, nur um an einem Schreibtisch zu sitzen, den er auch zu Hause hat, der handelt schlichtweg anachronistisch. Die Flexibilität, das "Arbeiten von überall", ist mittlerweile das schlagkräftigste Argument in unseren Bewerbungsgesprächen. Wer das ignoriert, wird den Fachkräftemangel in seiner härtesten Form spüren.
Dr. Schmidt: Wenn ich da kurz einhaken darf, Frau Lange. Das klingt in der Theorie der New-Work-Blase wunderbar. Aber schauen wir uns doch die soziologischen Fakten an. Ein Unternehmen ist mehr als eine Ansammlung von Einzelleistungen. Wir beobachten eine massive Erosion der Firmenkultur. Die Bindung an den Arbeitgeber schwindet, wenn der Kollege nur noch ein flackerndes Bild im Video-Call ist. Diese soziale Vereinsamung führt dazu, dass Mitarbeiter viel schneller kündigen, weil die emotionale Barriere fehlt.
Frau Weber: Aber ist nicht die Produktivität im Homeoffice laut Studien sogar gestiegen?
Dr. Schmidt: Das ist ein Trugschluss. Die quantitative Abarbeitung von Routineaufgaben mag funktionieren. Aber die qualitative Innovation, der Geistesblitz beim zufälligen Treffen im Flur, der lässt sich nicht digital simulieren. Kreativität ist ein chaotischer, physischer Prozess. Zoom-Meetings sind zu strukturiert für echte Innovation. Zudem darf man die prekäre Ergonomie in vielen Privathaushalten nicht vergessen – ein Küchentisch ersetzt kein professionelles Büro, was langfristig zu gesundheitlichen Ausfällen führt.
Frau Lange: Aber Herr Dr. Schmidt, das ist doch ein Scheinargument. Die Verantwortung für die Ausstattung kann man teilen. Der Kernpunkt ist doch die Kontrollillusion des Management. Viele Führungskräfte haben schlicht Angst vor dem Machtverlust, wenn sie ihre Mitarbeiter nicht mehr physisch "überwachen" können. Wir müssen weg von der "Absitz-Kultur". Führung im digitalen Zeitalter bedeutet, klare Zielvorgaben zu machen und die Qualität des Outputs zu bewerten, statt die Stunden auf dem Bürostuhl zu zählen. Vertrauen muss die Basis sein, nicht Überwachung.
Frau Weber: Dr. Schmidt, wie reagieren Sie auf den Vorwurf des Kontrollwahns?
Dr. Schmidt: Es geht nicht um Kontrolle, sondern um Fürsorge und Struktur. Wenn Berufs- und Privatleben verschwimmen, wenn abends um 22 Uhr noch Mails gecheckt werden, dann brennen die Leute aus. Die räumliche Trennung zwischen "Arbeitswelt" und "Rückzugsort" ist eine Errungenschaft des Arbeitnehmerschutzes, die wir gerade leichtfertig opfern.
Frau Lange: Einverstanden, die Entgrenzung ist eine Gefahr. Aber die Lösung ist nicht der Zwang zurück ins Büro, sondern eine neue Lernkultur. Übrigens profitieren auch die Firmen finanziell: Wer weniger Präsenzfläche braucht, senkt seine Mietkosten drastisch – ein Faktor, den gerade Controller in der aktuellen Wirtschaftslage nicht ignorieren sollten.
Frau Weber: Wenn wir ein Fazit ziehen: Ist die reine Präsenzpflicht tot?
Frau Lange: Ja, Flexibilität ist die Zukunft. Ein hybrides Modell, bei dem man sich gezielt für Workshops trifft, aber für die Konzentrationsarbeit zu Hause bleibt, ist der einzige Weg, der beide Seiten zufriedenstellt.
Dr. Schmidt: Nun, wenn man "Hybrid" so definiert, dass der Fokus wieder auf der Qualität der persönlichen Begegnung liegt, kann ich mit diesem Kompromiss leben. Er vereint die notwendige Struktur mit der modernen Freiheit.`,
                fragen: [
                    { frage: "22. Die soziale Isolierung im Homeoffice schadet der Identifikation mit dem Betrieb.", antworten: ["Frau Weber", "Dr. Schmidt", "Frau Lange"], richtig: 1, begruendung: "Dr. Schmidt: 'Diese soziale Vereinsamung führt dazu, dass Mitarbeiter viel schneller kündigen...'" },
                    { frage: "23. Kreative Prozesse lassen sich nicht erfolgreich in digitale Formate pressen.", antworten: ["Frau Weber", "Dr. Schmidt", "Frau Lange"], richtig: 1, begruendung: "Dr. Schmidt: 'Kreativität ist ein chaotischer, physischer Prozess. Zoom-Meetings sind zu strukturiert für echte Innovation.'" },
                    { frage: "24. Die Wahl des Arbeitsorts ist heute ein entscheidender Faktor im Recruiting.", antworten: ["Frau Weber", "Dr. Schmidt", "Frau Lange"], richtig: 2, begruendung: "Frau Lange: 'Die Flexibilität... ist mittlerweile das schlagkräftigste Argument in unseren Bewerbungsgesprächen.'" },
                    { frage: "25. Das Festhalten an Anwesenheitskontrolle ist ein Zeichen von mangelnder Modernität.", antworten: ["Frau Weber", "Dr. Schmidt", "Frau Lange"], richtig: 2, begruendung: "Frau Lange: 'Der Kernpunkt ist doch die Kontrollillusion des Managements... Wir müssen weg von der Absitz-Kultur.'" },
                    { frage: "26. Die häusliche Umgebung bietet oft keine professionellen Arbeitsbedingungen.", antworten: ["Frau Weber", "Dr. Schmidt", "Frau Lange"], richtig: 1, begruendung: "Dr. Schmidt: 'Zudem darf man die prekäre Ergonomie in vielen Privathaushalten nicht vergessen...'" },
                    { frage: "27. Nur ein hybrides Modell wird den unterschiedlichen Bedürfnissen gerecht.", antworten: ["Frau Weber", "Dr. Schmidt", "Frau Lange"], richtig: 2, begruendung: "Frau Lange: 'Ein hybrides Modell... ist der einzige Weg, der beide Seiten zufriedenstellt.'" },
                    { frage: "28. Das Management muss die Leistung anhand von Resultaten neu definieren.", antworten: ["Frau Weber", "Dr. Schmidt", "Frau Lange"], richtig: 2, begruendung: "Frau Lange: 'Führung im digitalen Zeitalter bedeutet, klare Zielvorgaben zu machen und die Qualität des Outputs zu bewerten...'" },
                    { frage: "29. Homeoffice spart den Unternehmen langfristig erhebliche Fixkosten für Büromieten.", antworten: ["Frau Weber", "Dr. Schmidt", "Frau Lange"], richtig: 2, begruendung: "Frau Lange: 'Wer weniger Präsenzfläche braucht, senkt seine Mietkosten drastisch...'" },
                    { frage: "30. Die Trennung von Privat- und Berufsleben wird durch Remote Work gefährlich instabil.", antworten: ["Frau Weber", "Dr. Schmidt", "Frau Lange"], richtig: 1, begruendung: "Dr. Schmidt: 'Wenn Berufs- und Privatleben verschwimmen... dann brennen die Leute aus.'" }
                ]
            },
            {
                teilName: "Teil 4: Der Experten-Vortrag (Attention Economy)",
                audioSrc: "audio/de1-teil4.mp3",
                transcript: `Sehr geehrte Damen und Herren, wir leben in einer Ära, in der nicht mehr das Kapital oder der Rohstoff Öl die wertvollsten Währungen sind. In unserer voll vernetzten Welt ist es die menschliche Aufmerksamkeit. Wir sprechen von der 'Attention Economy'.
Das Paradoxon unserer Zeit ist: Während die Menge an verfügbaren Daten exponentiell wächst, bleibt das menschliche Gehirn in seiner Kapazität, diese zu verarbeiten, biologisch limitiert. Plattformen wie TikTok, Instagram oder YouTube konkurrieren nicht nur um unser Geld, sondern um jede freie Sekunde unseres Bewusstseins. Dabei bedienen sie sich neurobiologischer Mechanismen: Durch algorithmische Belohnungssysteme wird in unserem Gehirn Dopamin ausgeschüttet – jedes 'Like', jede Benachrichtigung fungiert wie ein kleiner digitaler Spielautomat.
Besonders perfide ist das 'Infinite Scrolling'. Es ist kein Zufall, dass digitale Feeds kein Ende haben. Wo früher ein Zeitungsartikel endete oder ein Buchkapitel abgeschlossen war, gibt es heute keinen natürlichen Stopp-Moment mehr. Das führt dazu, dass wir in einen Zustand der kognitiven Trance verfallen. Die Folge ist eine Erosion unserer Fähigkeit zur tiefen Kontemplation. Wir verlernen das 'Deep Reading', das Versinken in komplexe Gedankengänge, und gewöhnen uns an eine fragmentierte, oberflächliche Wahrnehmung.
Dies hat auch gesellschaftliche Sprengkraft. Der Journalismus steht unter dem Diktat der Klickzahlen. Eine komplexe Analyse verkauft sich schlechter als eine reißerische Schlagzeile. So wird der öffentliche Diskurs zunehmend emotionalisiert und radikalisiert.
Was also tun? Wir können das Rad der Digitalisierung nicht zurückdrehen. Aber wir müssen eine neue Souveränität entwickeln. Das Bildungssystem ist hier in der Pflicht: Wir lehren unsere Kinder Mathematik und Sprachen, aber wir lehren sie nicht, wie man die eigene Aufmerksamkeit gegen manipulative Algorithmen verteidigt. Auch politisch brauchen wir Leitplanken – ein Verbot von Sucht-erzeugenden Designelementen in Apps wäre ein erster Schritt.
Am Ende des Tages liegt es jedoch an uns. Wir müssen begreifen, dass unsere Aufmerksamkeit unsere Freiheit ist. Wer nicht entscheidet, worauf er blickt, dem wird diese Entscheidung von einer künstlichen Intelligenz abgenommen. Und das ist ein Preis, den wir als aufgeklärte Gesellschaft nicht zahlen sollten.`,
                fragen: [
                    { frage: "31. Was ist die Kernaussage von Prof. Veith zu Beginn seines Vortrags?", antworten: ["A. Informationen sind das kostbarste Gut.", "B. In einer Welt des Informationsüberflusses ist menschliche Aufmerksamkeit die knappste Ressource.", "C. Schnelleres Lernen."], richtig: 1, begruendung: "Vortrag: 'In unserer voll vernetzten Welt ist es die menschliche Aufmerksamkeit.'" },
                    { frage: "32. Warum nutzen Plattformen „algorithmische Belohnungssysteme“?", antworten: ["A. Relevante Bildungsinhalte.", "B. Um die Verweildauer der Nutzer durch psychologische Reize künstlich zu verlängern.", "C. Gegen Falschinformationen."], richtig: 1, begruendung: "Vortrag: 'Durch algorithmische Belohnungssysteme wird in unserem Gehirn Dopamin ausgeschüttet...'" },
                    { frage: "33. Welchen Einfluss hat die „Aufmerksamkeitsökonomie“ auf den Journalismus?", antworten: ["A. Nachrichten werden kürzer und oberflächlicher, um die Klickzahlen zu erhöhen.", "B. Tiefgründige Recherchen.", "C. Höhere Qualität."], richtig: 0, begruendung: "Vortrag: 'Eine komplexe Analyse verkauft sich schlechter als eine reißerische Schlagzeile.'" },
                    { frage: "34. Was versteht der Redner unter dem Begriff „Infinite Scrolling“?", antworten: ["A. Archivierungsmethode.", "B. Ein technisches Design, das das natürliche Ende einer Informationseinheit verhindert.", "C. Lesehilfe."], richtig: 1, begruendung: "Vortrag: '...gibt es heute keinen natürlichen Stopp-Moment mehr.'" },
                    { frage: "35. Welche gesundheitlichen Folgen werden im Vortrag explizit genannt?", antworten: ["A. Rückenschmerzen.", "B. Chronische Konzentrationsstörungen und eine verminderte Fähigkeit zur Tiefenreflexion.", "C. Bessere Reaktion."], richtig: 1, begruendung: "Vortrag: 'Die Folge ist eine Erosion unserer Fähigkeit zur tiefen Kontemplation. Wir verlernen das Deep Reading...'" },
                    { frage: "36. Wie reagiert die Wirtschaft laut Prof. Veith auf diesen Trend?", antworten: ["A. Verzicht auf Werbung.", "B. Emotionale Schockmomente.", "C. Firmen investieren Milliarden, um Sekunden der menschlichen Konzentration zu „kaufen“."], richtig: 2, begruendung: "Vortrag: 'Plattformen... konkurrieren nicht nur um unser Geld, sondern um jede freie Sekunde unseres Bewusstseins.'" },
                    { frage: "37. Was kritisiert der Experte am Bildungssektor?", antworten: ["A. Zu wenig Computer.", "B. Dass Lehrpläne die Vermittlung von „Aufmerksamkeitsdisziplin“ bisher vernachlässigen.", "C. Lehrer im Social Media."], richtig: 1, begruendung: "Vortrag: 'Wir lehren unsere Kinder Mathematik... aber wir lehren sie nicht, wie man die eigene Aufmerksamkeit verteidigt.'" },
                    { frage: "38. Welchen Lösungsvorschlag macht der Redner auf individueller Ebene?", antworten: ["A. Kompletter Verzicht.", "B. Die bewusste Gestaltung von „digitalen Fastenperioden“ und analogen Freiräumen.", "C. Apps blockieren."], richtig: 1, begruendung: "Vortrag: 'Wir müssen eine neue Souveränität entwickeln...'" },
                    { frage: "39. Welche Rolle sollte der Staat laut Prof. Veith einnehmen?", antworten: ["A. Netzwerke verbieten.", "B. Er muss strengere Richtlinien für manipulatives Design in der Softwareentwicklung vorgeben.", "C. Kostenloses Internet."], richtig: 1, begruendung: "Vortrag: '...ein Verbot von Sucht-erzeugenden Designelementen in Apps wäre ein erster Schritt.'" },
                    { frage: "40. Welches Fazit zieht der Redner am Ende?", antworten: ["A. Digitale Revolution gescheitert.", "B. Wir müssen die Kontrolle über unsere Wahrnehmung von den Algorithmen zurückerobern.", "C. Psyche passt sich an."], richtig: 1, begruendung: "Vortrag: 'Wir müssen begreifen, dass unsere Aufmerksamkeit unsere Freiheit ist.'" }
                ]
            },
            {
                teilName: "Teil 5: Wissenschaftlicher Diskurs",
                audioSrc: "audio/de1-teil5.mp3",
                transcript: `Meine Damen und Herren, lassen Sie uns heute ein Tabu der modernen Ökonomie brechen: Das Dogma des ewigen Wachstums. Seit der industriellen Revolution ist unser gesamtes System darauf programmiert, dass das BIP (Bruttoinlandsprodukt) Jahr für Jahr steigen muss. Doch wir stoßen an die planetaren Grenzen. Das Paradoxon, das wir beobachten, ist der sogenannte 'Rebound-Effekt'. Wir bauen zwar Autos, die weniger Benzin verbrauchen, aber was passiert? Die Menschen fahren mehr Kilometer oder kaufen größere SUVs. Am Ende ist der absolute Ressourcenverbrauch höher als zuvor. Effizienz allein ist also eine Sackgasse, wenn sie nicht mit einer kulturellen Strategie der Genügsamkeit – der Suffizienz – einhergeht.
Die Verfechter des 'Grünen Wachstums' versprechen uns, dass wir Technik und Ökologie versöhnen können. Doch das ist, bei allem Respekt, eine Beruhigungspille für das schlechte Gewissen der Konsumgesellschaft. Wir können die Produktion nicht unendlich 'entkoppeln'. Jedes produzierte Gut, auch ein Elektroauto, benötigt seltene Erden, Wasser und Energie. Wir müssen uns fragen: Wann ist es genug? In der aktuellen Wirtschaftsforschung nennen wir das die 'Post-Wachstumsökonomie'. Es geht nicht um Armut, sondern um eine Befreiung vom Ballast.
(Dr. Martinez): Ich möchte Herrn Professor von Hagens hier ergänzen, aber auch einen kritischen Akzent setzen. Das Problem ist nicht nur die ökologische Grenze, sondern die psychologische Erschöpfung. Wir arbeiten 40 Stunden oder mehr, um Dinge zu kaufen, die wir nicht brauchen, um Leute zu beeindrucken, die wir nicht mögen. Das ist eine Form von Hamsterrad-Ökonomie.
Wenn wir über 'Wohlstand' reden, müssen wir ihn neu definieren. Echter Wohlstand im 21. Jahrhundert ist nicht der dritte Fernseher oder das neueste Smartphone alle zwei Jahre. Echter Wohlstand ist Zeitsouveränität. Die Fähigkeit, weniger zu arbeiten, mehr Zeit für Bildung, Familie und zivilgesellschaftliches Engagement zu haben. Doch hier liegt die Krux: Unser Renten- und Sozialsystem ist so konstruiert, dass es ohne Wachstum kollabiert. Wenn die Wirtschaft schrumpft, steigen die Arbeitslosenzahlen. Das ist die fatale Logik, aus der wir ausbrechen müssen. Wir brauchen ein System, das stabil ist, auch wenn es nicht wächst. Das erfordert eine radikale Umverteilung von Arbeit und Vermögen.
(Prof. von Hagens): Exakt. Und das führt uns zur Frage der globalen Gerechtigkeit. Wir im globalen Norden können nicht von den Schwellenländern verlangen, auf Wachstum zu verzichten, während wir unseren Lebensstandard auf Kosten ihrer Ressourcen verteidigen. Eine Post-Wachstumsgesellschaft im Westen ist die moralische Voraussetzung dafür, dass der Rest der Welt überhaupt eine Chance auf eine würdige Entwicklung hat. Wir müssen lernen, mit weniger materiellen Gütern ein besseres Leben zu führen – eine 'Eleganz des Weglassens', wenn Sie so wollen.`,
                fragen: [
                    { frage: "41. Welches Paradoxon beschreibt Prof. von Hagens zu Beginn?", antworten: ["A. Menschen konsumieren weniger.", "B. Wachstum steigt, Lebenszufriedenheit stagniert.", "C. Dass technische Innovationen den Ressourcenverbrauch nicht senken, sondern steigern."], richtig: 2, begruendung: "Prof. von Hagens: 'Das Paradoxon... ist der Rebound-Effekt... am Ende ist der absolute Ressourcenverbrauch höher als zuvor.'" },
                    { frage: "42. Was ist die Hauptkritik am „Grünen Wachstum“?", antworten: ["A. Zu teuer.", "B. Es ist eine Illusion, da die Effizienzgewinne durch Mehrkonsum aufgefressen werden.", "C. Technik nicht weit genug."], richtig: 1, begruendung: "Prof. von Hagens: 'Doch das ist... eine Beruhigungspille für das schlechte Gewissen... Wir können die Produktion nicht unendlich entkoppeln.'" },
                    { frage: "43. Welchen neuen Wohlstandsbegriff schlägt Dr. Martinez vor?", antworten: ["A. Luxusgüter.", "B. Die Souveränität über die eigene Zeit und soziale Bindungen.", "C. Grundeinkommen."], richtig: 1, begruendung: "Dr. Martinez: 'Echter Wohlstand ist Zeitsouveränität. Die Fähigkeit, weniger zu arbeiten, mehr Zeit für Bildung, Familie... zu haben.'" }
                ]
            }
        ]
    }
];
